/**
 * lodgea-js
 * LODGEA SDK for javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/com.lodgea/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/com.lodgea/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LodgeaJs);
  }
}(this, function(expect, LodgeaJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LodgeaJs.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('availabilitySearchPost', function() {
      it('should call availabilitySearchPost successfully', function(done) {
        //uncomment below and update the code to test availabilitySearchPost
        //instance.availabilitySearchPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('locationSearchPost', function() {
      it('should call locationSearchPost successfully', function(done) {
        //uncomment below and update the code to test locationSearchPost
        //instance.locationSearchPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('propertiesGet', function() {
      it('should call propertiesGet successfully', function(done) {
        //uncomment below and update the code to test propertiesGet
        //instance.propertiesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('propertiesPropertyIdAvailabilityGet', function() {
      it('should call propertiesPropertyIdAvailabilityGet successfully', function(done) {
        //uncomment below and update the code to test propertiesPropertyIdAvailabilityGet
        //instance.propertiesPropertyIdAvailabilityGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('propertiesPropertyIdGet', function() {
      it('should call propertiesPropertyIdGet successfully', function(done) {
        //uncomment below and update the code to test propertiesPropertyIdGet
        //instance.propertiesPropertyIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
