/**
 * lodgea-js
 * LODGEA SDK for Javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AvailablePropertiesInner1LowestPrice model module.
 * @module com.lodgea/com.lodgea.model/AvailablePropertiesInner1LowestPrice
 * @version 1.1.0
 */
class AvailablePropertiesInner1LowestPrice {
    /**
     * Constructs a new <code>AvailablePropertiesInner1LowestPrice</code>.
     * An object outlining the stay with the lowest available price point for this property.
     * @alias module:com.lodgea/com.lodgea.model/AvailablePropertiesInner1LowestPrice
     * @param amount {Number} The amount of the lowest price.
     * @param currencyCode {module:com.lodgea/com.lodgea.model/AvailablePropertiesInner1LowestPrice.CurrencyCodeEnum} The currency code for the given amount.<p>See also <a href=\"#currencycodes\">in the appendix</a>.</p>
     * @param arrivalDate {Number} Arrival date for the given price as unix timestamp (seconds).
     * @param returnDate {Number} Departure date for the given price as unix timestamp (seconds).
     * @param lengthOfStay {Number} The amount of nights of stay this price is for
     */
    constructor(amount, currencyCode, arrivalDate, returnDate, lengthOfStay) { 
        
        AvailablePropertiesInner1LowestPrice.initialize(this, amount, currencyCode, arrivalDate, returnDate, lengthOfStay);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, currencyCode, arrivalDate, returnDate, lengthOfStay) { 
        obj['amount'] = amount;
        obj['currencyCode'] = currencyCode;
        obj['arrivalDate'] = arrivalDate;
        obj['returnDate'] = returnDate;
        obj['lengthOfStay'] = lengthOfStay;
    }

    /**
     * Constructs a <code>AvailablePropertiesInner1LowestPrice</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.lodgea/com.lodgea.model/AvailablePropertiesInner1LowestPrice} obj Optional instance to populate.
     * @return {module:com.lodgea/com.lodgea.model/AvailablePropertiesInner1LowestPrice} The populated <code>AvailablePropertiesInner1LowestPrice</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AvailablePropertiesInner1LowestPrice();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currencyCode')) {
                obj['currencyCode'] = ApiClient.convertToType(data['currencyCode'], 'String');
            }
            if (data.hasOwnProperty('arrivalDate')) {
                obj['arrivalDate'] = ApiClient.convertToType(data['arrivalDate'], 'Number');
            }
            if (data.hasOwnProperty('returnDate')) {
                obj['returnDate'] = ApiClient.convertToType(data['returnDate'], 'Number');
            }
            if (data.hasOwnProperty('lengthOfStay')) {
                obj['lengthOfStay'] = ApiClient.convertToType(data['lengthOfStay'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The amount of the lowest price.
 * @member {Number} amount
 */
AvailablePropertiesInner1LowestPrice.prototype['amount'] = undefined;

/**
 * The currency code for the given amount.<p>See also <a href=\"#currencycodes\">in the appendix</a>.</p>
 * @member {module:com.lodgea/com.lodgea.model/AvailablePropertiesInner1LowestPrice.CurrencyCodeEnum} currencyCode
 */
AvailablePropertiesInner1LowestPrice.prototype['currencyCode'] = undefined;

/**
 * Arrival date for the given price as unix timestamp (seconds).
 * @member {Number} arrivalDate
 */
AvailablePropertiesInner1LowestPrice.prototype['arrivalDate'] = undefined;

/**
 * Departure date for the given price as unix timestamp (seconds).
 * @member {Number} returnDate
 */
AvailablePropertiesInner1LowestPrice.prototype['returnDate'] = undefined;

/**
 * The amount of nights of stay this price is for
 * @member {Number} lengthOfStay
 */
AvailablePropertiesInner1LowestPrice.prototype['lengthOfStay'] = undefined;





/**
 * Allowed values for the <code>currencyCode</code> property.
 * @enum {String}
 * @readonly
 */
AvailablePropertiesInner1LowestPrice['CurrencyCodeEnum'] = {

    /**
     * value: "AED"
     * @const
     */
    "AED": "AED",

    /**
     * value: "ARS"
     * @const
     */
    "ARS": "ARS",

    /**
     * value: "AUD"
     * @const
     */
    "AUD": "AUD",

    /**
     * value: "AZN"
     * @const
     */
    "AZN": "AZN",

    /**
     * value: "BGN"
     * @const
     */
    "BGN": "BGN",

    /**
     * value: "BHD"
     * @const
     */
    "BHD": "BHD",

    /**
     * value: "BRL"
     * @const
     */
    "BRL": "BRL",

    /**
     * value: "CAD"
     * @const
     */
    "CAD": "CAD",

    /**
     * value: "CHF"
     * @const
     */
    "CHF": "CHF",

    /**
     * value: "CLP"
     * @const
     */
    "CLP": "CLP",

    /**
     * value: "CNY"
     * @const
     */
    "CNY": "CNY",

    /**
     * value: "COP"
     * @const
     */
    "COP": "COP",

    /**
     * value: "CZK"
     * @const
     */
    "CZK": "CZK",

    /**
     * value: "DKK"
     * @const
     */
    "DKK": "DKK",

    /**
     * value: "EGP"
     * @const
     */
    "EGP": "EGP",

    /**
     * value: "EUR"
     * @const
     */
    "EUR": "EUR",

    /**
     * value: "FJD"
     * @const
     */
    "FJD": "FJD",

    /**
     * value: "GBP"
     * @const
     */
    "GBP": "GBP",

    /**
     * value: "GEL"
     * @const
     */
    "GEL": "GEL",

    /**
     * value: "HKD"
     * @const
     */
    "HKD": "HKD",

    /**
     * value: "HUF"
     * @const
     */
    "HUF": "HUF",

    /**
     * value: "IDR"
     * @const
     */
    "IDR": "IDR",

    /**
     * value: "ILS"
     * @const
     */
    "ILS": "ILS",

    /**
     * value: "INR"
     * @const
     */
    "INR": "INR",

    /**
     * value: "JOD"
     * @const
     */
    "JOD": "JOD",

    /**
     * value: "JPY"
     * @const
     */
    "JPY": "JPY",

    /**
     * value: "KRW"
     * @const
     */
    "KRW": "KRW",

    /**
     * value: "KWD"
     * @const
     */
    "KWD": "KWD",

    /**
     * value: "KZT"
     * @const
     */
    "KZT": "KZT",

    /**
     * value: "MDL"
     * @const
     */
    "MDL": "MDL",

    /**
     * value: "MXN"
     * @const
     */
    "MXN": "MXN",

    /**
     * value: "MYR"
     * @const
     */
    "MYR": "MYR",

    /**
     * value: "NAD"
     * @const
     */
    "NAD": "NAD",

    /**
     * value: "NOK"
     * @const
     */
    "NOK": "NOK",

    /**
     * value: "NZD"
     * @const
     */
    "NZD": "NZD",

    /**
     * value: "OMR"
     * @const
     */
    "OMR": "OMR",

    /**
     * value: "PLN"
     * @const
     */
    "PLN": "PLN",

    /**
     * value: "QAR"
     * @const
     */
    "QAR": "QAR",

    /**
     * value: "RON"
     * @const
     */
    "RON": "RON",

    /**
     * value: "RUB"
     * @const
     */
    "RUB": "RUB",

    /**
     * value: "SAR"
     * @const
     */
    "SAR": "SAR",

    /**
     * value: "SEK"
     * @const
     */
    "SEK": "SEK",

    /**
     * value: "SGD"
     * @const
     */
    "SGD": "SGD",

    /**
     * value: "THB"
     * @const
     */
    "THB": "THB",

    /**
     * value: "TRY"
     * @const
     */
    "TRY": "TRY",

    /**
     * value: "TWD"
     * @const
     */
    "TWD": "TWD",

    /**
     * value: "UAH"
     * @const
     */
    "UAH": "UAH",

    /**
     * value: "USD"
     * @const
     */
    "USD": "USD",

    /**
     * value: "XOF"
     * @const
     */
    "XOF": "XOF",

    /**
     * value: "ZAR"
     * @const
     */
    "ZAR": "ZAR"
};



export default AvailablePropertiesInner1LowestPrice;

