/**
 * lodgea-js
 * LODGEA SDK for javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse2003PolicyInfo from './InlineResponse2003PolicyInfo';
import InlineResponse2003RatePlanList from './InlineResponse2003RatePlanList';

/**
 * The InlineResponse2003ProductList model module.
 * @module com.lodgea/com.lodgea.model/InlineResponse2003ProductList
 * @version 1.2.0
 */
class InlineResponse2003ProductList {
    /**
     * Constructs a new <code>InlineResponse2003ProductList</code>.
     * A list of available products for this property.
     * @alias module:com.lodgea/com.lodgea.model/InlineResponse2003ProductList
     * @param propertyId {String} The ID of the property.
     * @param name {String} The name of the product.
     * @param mealPlanList {Array.<module:com.lodgea/com.lodgea.model/InlineResponse2003ProductList.MealPlanListEnum>} A list of meal type codes included in this product.
     * @param roomTypeList {Array.<String>} An array of strings describing the room types included in this product.
     * @param ratePlanList {Array.<module:com.lodgea/com.lodgea.model/InlineResponse2003RatePlanList>} The rate plans for this product.
     */
    constructor(propertyId, name, mealPlanList, roomTypeList, ratePlanList) { 
        
        InlineResponse2003ProductList.initialize(this, propertyId, name, mealPlanList, roomTypeList, ratePlanList);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, propertyId, name, mealPlanList, roomTypeList, ratePlanList) { 
        obj['propertyId'] = propertyId;
        obj['name'] = name;
        obj['mealPlanList'] = mealPlanList;
        obj['roomTypeList'] = roomTypeList;
        obj['ratePlanList'] = ratePlanList;
    }

    /**
     * Constructs a <code>InlineResponse2003ProductList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.lodgea/com.lodgea.model/InlineResponse2003ProductList} obj Optional instance to populate.
     * @return {module:com.lodgea/com.lodgea.model/InlineResponse2003ProductList} The populated <code>InlineResponse2003ProductList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2003ProductList();

            if (data.hasOwnProperty('propertyId')) {
                obj['propertyId'] = ApiClient.convertToType(data['propertyId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('mealPlanList')) {
                obj['mealPlanList'] = ApiClient.convertToType(data['mealPlanList'], ['Number']);
            }
            if (data.hasOwnProperty('roomTypeList')) {
                obj['roomTypeList'] = ApiClient.convertToType(data['roomTypeList'], ['String']);
            }
            if (data.hasOwnProperty('isLOSPricing')) {
                obj['isLOSPricing'] = ApiClient.convertToType(data['isLOSPricing'], 'Boolean');
            }
            if (data.hasOwnProperty('isOBPPricing')) {
                obj['isOBPPricing'] = ApiClient.convertToType(data['isOBPPricing'], 'Boolean');
            }
            if (data.hasOwnProperty('ratePlanList')) {
                obj['ratePlanList'] = ApiClient.convertToType(data['ratePlanList'], [InlineResponse2003RatePlanList]);
            }
            if (data.hasOwnProperty('policyInfo')) {
                obj['policyInfo'] = InlineResponse2003PolicyInfo.constructFromObject(data['policyInfo']);
            }
        }
        return obj;
    }


}

/**
 * The ID of the property.
 * @member {String} propertyId
 */
InlineResponse2003ProductList.prototype['propertyId'] = undefined;

/**
 * The name of the product.
 * @member {String} name
 */
InlineResponse2003ProductList.prototype['name'] = undefined;

/**
 * A list of meal type codes included in this product.
 * @member {Array.<module:com.lodgea/com.lodgea.model/InlineResponse2003ProductList.MealPlanListEnum>} mealPlanList
 */
InlineResponse2003ProductList.prototype['mealPlanList'] = undefined;

/**
 * An array of strings describing the room types included in this product.
 * @member {Array.<String>} roomTypeList
 */
InlineResponse2003ProductList.prototype['roomTypeList'] = undefined;

/**
 * Whether this product is length of stay pricing.
 * @member {Boolean} isLOSPricing
 */
InlineResponse2003ProductList.prototype['isLOSPricing'] = undefined;

/**
 * Whether this product is occupancy based pricing.
 * @member {Boolean} isOBPPricing
 */
InlineResponse2003ProductList.prototype['isOBPPricing'] = undefined;

/**
 * The rate plans for this product.
 * @member {Array.<module:com.lodgea/com.lodgea.model/InlineResponse2003RatePlanList>} ratePlanList
 */
InlineResponse2003ProductList.prototype['ratePlanList'] = undefined;

/**
 * @member {module:com.lodgea/com.lodgea.model/InlineResponse2003PolicyInfo} policyInfo
 */
InlineResponse2003ProductList.prototype['policyInfo'] = undefined;





/**
 * Allowed values for the <code>mealPlanList</code> property.
 * @enum {Number}
 * @readonly
 */
InlineResponse2003ProductList['MealPlanListEnum'] = {

    /**
     * value: 0
     * @const
     */
    "0": 0,

    /**
     * value: 1
     * @const
     */
    "1": 1,

    /**
     * value: 2
     * @const
     */
    "2": 2,

    /**
     * value: 3
     * @const
     */
    "3": 3,

    /**
     * value: 4
     * @const
     */
    "4": 4,

    /**
     * value: 5
     * @const
     */
    "5": 5,

    /**
     * value: 6
     * @const
     */
    "6": 6,

    /**
     * value: 7
     * @const
     */
    "7": 7,

    /**
     * value: 8
     * @const
     */
    "8": 8,

    /**
     * value: 9
     * @const
     */
    "9": 9,

    /**
     * value: 10
     * @const
     */
    "10": 10,

    /**
     * value: 11
     * @const
     */
    "11": 11,

    /**
     * value: 12
     * @const
     */
    "12": 12,

    /**
     * value: 14
     * @const
     */
    "14": 14,

    /**
     * value: 15
     * @const
     */
    "15": 15,

    /**
     * value: 16
     * @const
     */
    "16": 16,

    /**
     * value: 17
     * @const
     */
    "17": 17,

    /**
     * value: 18
     * @const
     */
    "18": 18,

    /**
     * value: 19
     * @const
     */
    "19": 19,

    /**
     * value: 20
     * @const
     */
    "20": 20,

    /**
     * value: 21
     * @const
     */
    "21": 21,

    /**
     * value: 22
     * @const
     */
    "22": 22,

    /**
     * value: 23
     * @const
     */
    "23": 23,

    /**
     * value: 24
     * @const
     */
    "24": 24,

    /**
     * value: 90001
     * @const
     */
    "90001": 90001
};



export default InlineResponse2003ProductList;

