/**
 * lodgea-js
 * LODGEA SDK for javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2003PropertyRecordModified model module.
 * @module com.lodgea/com.lodgea.model/InlineResponse2003PropertyRecordModified
 * @version 1.2.0
 */
class InlineResponse2003PropertyRecordModified {
    /**
     * Constructs a new <code>InlineResponse2003PropertyRecordModified</code>.
     * Information regarding the last modification of the property object.
     * @alias module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyRecordModified
     * @param user {String} The user that performed the edit action on the property.
     * @param tenant {String} The tenant for which the user performed the edit action on the property.
     * @param time {Number} The timestamp at which the edit action was performed.
     */
    constructor(user, tenant, time) { 
        
        InlineResponse2003PropertyRecordModified.initialize(this, user, tenant, time);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, user, tenant, time) { 
        obj['user'] = user;
        obj['tenant'] = tenant;
        obj['time'] = time;
    }

    /**
     * Constructs a <code>InlineResponse2003PropertyRecordModified</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyRecordModified} obj Optional instance to populate.
     * @return {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyRecordModified} The populated <code>InlineResponse2003PropertyRecordModified</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2003PropertyRecordModified();

            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'String');
            }
            if (data.hasOwnProperty('tenant')) {
                obj['tenant'] = ApiClient.convertToType(data['tenant'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The user that performed the edit action on the property.
 * @member {String} user
 */
InlineResponse2003PropertyRecordModified.prototype['user'] = undefined;

/**
 * The tenant for which the user performed the edit action on the property.
 * @member {String} tenant
 */
InlineResponse2003PropertyRecordModified.prototype['tenant'] = undefined;

/**
 * The role of the user that performed the edit action on the property.
 * @member {String} role
 */
InlineResponse2003PropertyRecordModified.prototype['role'] = undefined;

/**
 * The timestamp at which the edit action was performed.
 * @member {Number} time
 */
InlineResponse2003PropertyRecordModified.prototype['time'] = undefined;






export default InlineResponse2003PropertyRecordModified;

