/**
 * lodgea-js
 * LODGEA SDK for javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2003PropertyOperationTimeList model module.
 * @module com.lodgea/com.lodgea.model/InlineResponse2003PropertyOperationTimeList
 * @version 1.2.0
 */
class InlineResponse2003PropertyOperationTimeList {
    /**
     * Constructs a new <code>InlineResponse2003PropertyOperationTimeList</code>.
     * @alias module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyOperationTimeList
     * @param start {Number} The start time of operation in milliseconds.
     * @param end {Number} The end time of operation in milliseconds.
     * @param monday {Boolean} Indicates whether the operation is open on Monday.
     * @param tuesday {Boolean} Indicates whether the operation is open on Tuesday.
     * @param wednesday {Boolean} Indicates whether the operation is open on Wednesday.
     * @param thursday {Boolean} Indicates whether the operation is open on Thursday.
     * @param friday {Boolean} Indicates whether the operation is open on Friday.
     * @param saturday {Boolean} Indicates whether the operation is open on Saturday.
     * @param sunday {Boolean} Indicates whether the operation is open on Sunday.
     */
    constructor(start, end, monday, tuesday, wednesday, thursday, friday, saturday, sunday) { 
        
        InlineResponse2003PropertyOperationTimeList.initialize(this, start, end, monday, tuesday, wednesday, thursday, friday, saturday, sunday);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, start, end, monday, tuesday, wednesday, thursday, friday, saturday, sunday) { 
        obj['start'] = start;
        obj['end'] = end;
        obj['monday'] = monday;
        obj['tuesday'] = tuesday;
        obj['wednesday'] = wednesday;
        obj['thursday'] = thursday;
        obj['friday'] = friday;
        obj['saturday'] = saturday;
        obj['sunday'] = sunday;
    }

    /**
     * Constructs a <code>InlineResponse2003PropertyOperationTimeList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyOperationTimeList} obj Optional instance to populate.
     * @return {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyOperationTimeList} The populated <code>InlineResponse2003PropertyOperationTimeList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2003PropertyOperationTimeList();

            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], 'Number');
            }
            if (data.hasOwnProperty('end')) {
                obj['end'] = ApiClient.convertToType(data['end'], 'Number');
            }
            if (data.hasOwnProperty('monday')) {
                obj['monday'] = ApiClient.convertToType(data['monday'], 'Boolean');
            }
            if (data.hasOwnProperty('tuesday')) {
                obj['tuesday'] = ApiClient.convertToType(data['tuesday'], 'Boolean');
            }
            if (data.hasOwnProperty('wednesday')) {
                obj['wednesday'] = ApiClient.convertToType(data['wednesday'], 'Boolean');
            }
            if (data.hasOwnProperty('thursday')) {
                obj['thursday'] = ApiClient.convertToType(data['thursday'], 'Boolean');
            }
            if (data.hasOwnProperty('friday')) {
                obj['friday'] = ApiClient.convertToType(data['friday'], 'Boolean');
            }
            if (data.hasOwnProperty('saturday')) {
                obj['saturday'] = ApiClient.convertToType(data['saturday'], 'Boolean');
            }
            if (data.hasOwnProperty('sunday')) {
                obj['sunday'] = ApiClient.convertToType(data['sunday'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * The start time of operation in milliseconds.
 * @member {Number} start
 */
InlineResponse2003PropertyOperationTimeList.prototype['start'] = undefined;

/**
 * The end time of operation in milliseconds.
 * @member {Number} end
 */
InlineResponse2003PropertyOperationTimeList.prototype['end'] = undefined;

/**
 * Indicates whether the operation is open on Monday.
 * @member {Boolean} monday
 */
InlineResponse2003PropertyOperationTimeList.prototype['monday'] = undefined;

/**
 * Indicates whether the operation is open on Tuesday.
 * @member {Boolean} tuesday
 */
InlineResponse2003PropertyOperationTimeList.prototype['tuesday'] = undefined;

/**
 * Indicates whether the operation is open on Wednesday.
 * @member {Boolean} wednesday
 */
InlineResponse2003PropertyOperationTimeList.prototype['wednesday'] = undefined;

/**
 * Indicates whether the operation is open on Thursday.
 * @member {Boolean} thursday
 */
InlineResponse2003PropertyOperationTimeList.prototype['thursday'] = undefined;

/**
 * Indicates whether the operation is open on Friday.
 * @member {Boolean} friday
 */
InlineResponse2003PropertyOperationTimeList.prototype['friday'] = undefined;

/**
 * Indicates whether the operation is open on Saturday.
 * @member {Boolean} saturday
 */
InlineResponse2003PropertyOperationTimeList.prototype['saturday'] = undefined;

/**
 * Indicates whether the operation is open on Sunday.
 * @member {Boolean} sunday
 */
InlineResponse2003PropertyOperationTimeList.prototype['sunday'] = undefined;






export default InlineResponse2003PropertyOperationTimeList;

