/**
 * lodgea-js
 * LODGEA SDK for javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse200List from './InlineResponse200List';

/**
 * The InlineResponse200 model module.
 * @module com.lodgea/com.lodgea.model/InlineResponse200
 * @version 1.2.0
 */
class InlineResponse200 {
    /**
     * Constructs a new <code>InlineResponse200</code>.
     * @alias module:com.lodgea/com.lodgea.model/InlineResponse200
     * @param languageCode {String} The language code of the language in which the descriptive texts for each found location are returned.<p>Please note that beside the general restrictions listed below only languages configured during system setup for your respective tenant are allowed.</p><p>See also <a href=\"#isolanguage-codes\">in the appendix</a>.</p>
     * @param list {Array.<module:com.lodgea/com.lodgea.model/InlineResponse200List>} A list of available properties matching the given criteria.
     */
    constructor(languageCode, list) { 
        
        InlineResponse200.initialize(this, languageCode, list);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, languageCode, list) { 
        obj['languageCode'] = languageCode;
        obj['list'] = list;
    }

    /**
     * Constructs a <code>InlineResponse200</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.lodgea/com.lodgea.model/InlineResponse200} obj Optional instance to populate.
     * @return {module:com.lodgea/com.lodgea.model/InlineResponse200} The populated <code>InlineResponse200</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200();

            if (data.hasOwnProperty('languageCode')) {
                obj['languageCode'] = ApiClient.convertToType(data['languageCode'], 'String');
            }
            if (data.hasOwnProperty('list')) {
                obj['list'] = ApiClient.convertToType(data['list'], [InlineResponse200List]);
            }
        }
        return obj;
    }


}

/**
 * The language code of the language in which the descriptive texts for each found location are returned.<p>Please note that beside the general restrictions listed below only languages configured during system setup for your respective tenant are allowed.</p><p>See also <a href=\"#isolanguage-codes\">in the appendix</a>.</p>
 * @member {String} languageCode
 */
InlineResponse200.prototype['languageCode'] = undefined;

/**
 * A list of available properties matching the given criteria.
 * @member {Array.<module:com.lodgea/com.lodgea.model/InlineResponse200List>} list
 */
InlineResponse200.prototype['list'] = undefined;






export default InlineResponse200;

