/**
 * lodgea-js
 * LODGEA SDK for javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2001MediaList model module.
 * @module com.lodgea/com.lodgea.model/InlineResponse2001MediaList
 * @version 1.2.0
 */
class InlineResponse2001MediaList {
    /**
     * Constructs a new <code>InlineResponse2001MediaList</code>.
     * @alias module:com.lodgea/com.lodgea.model/InlineResponse2001MediaList
     * @param tagList {Array.<module:com.lodgea/com.lodgea.model/InlineResponse2001MediaList.TagListEnum>} A list of tag codes for the media.<p>See also <a href=\"#imagetype-codes\">in the appendix</a>.</p>
     * @param isMainImage {Boolean} Whether the media is the main image for the property.
     * @param url {String} The URL for the media.
     * @param sortOrder {Number} The sort order for the media.
     */
    constructor(tagList, isMainImage, url, sortOrder) { 
        
        InlineResponse2001MediaList.initialize(this, tagList, isMainImage, url, sortOrder);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tagList, isMainImage, url, sortOrder) { 
        obj['tagList'] = tagList;
        obj['isMainImage'] = isMainImage;
        obj['url'] = url;
        obj['sortOrder'] = sortOrder;
    }

    /**
     * Constructs a <code>InlineResponse2001MediaList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.lodgea/com.lodgea.model/InlineResponse2001MediaList} obj Optional instance to populate.
     * @return {module:com.lodgea/com.lodgea.model/InlineResponse2001MediaList} The populated <code>InlineResponse2001MediaList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2001MediaList();

            if (data.hasOwnProperty('tagList')) {
                obj['tagList'] = ApiClient.convertToType(data['tagList'], ['Number']);
            }
            if (data.hasOwnProperty('isMainImage')) {
                obj['isMainImage'] = ApiClient.convertToType(data['isMainImage'], 'Boolean');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('sortOrder')) {
                obj['sortOrder'] = ApiClient.convertToType(data['sortOrder'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * A list of tag codes for the media.<p>See also <a href=\"#imagetype-codes\">in the appendix</a>.</p>
 * @member {Array.<module:com.lodgea/com.lodgea.model/InlineResponse2001MediaList.TagListEnum>} tagList
 */
InlineResponse2001MediaList.prototype['tagList'] = undefined;

/**
 * Whether the media is the main image for the property.
 * @member {Boolean} isMainImage
 */
InlineResponse2001MediaList.prototype['isMainImage'] = undefined;

/**
 * The URL for the media.
 * @member {String} url
 */
InlineResponse2001MediaList.prototype['url'] = undefined;

/**
 * The sort order for the media.
 * @member {Number} sortOrder
 */
InlineResponse2001MediaList.prototype['sortOrder'] = undefined;





/**
 * Allowed values for the <code>tagList</code> property.
 * @enum {Number}
 * @readonly
 */
InlineResponse2001MediaList['TagListEnum'] = {

    /**
     * value: 1
     * @const
     */
    "1": 1,

    /**
     * value: 2
     * @const
     */
    "2": 2,

    /**
     * value: 3
     * @const
     */
    "3": 3,

    /**
     * value: 4
     * @const
     */
    "4": 4,

    /**
     * value: 5
     * @const
     */
    "5": 5,

    /**
     * value: 6
     * @const
     */
    "6": 6,

    /**
     * value: 7
     * @const
     */
    "7": 7,

    /**
     * value: 8
     * @const
     */
    "8": 8,

    /**
     * value: 10
     * @const
     */
    "10": 10,

    /**
     * value: 11
     * @const
     */
    "11": 11,

    /**
     * value: 13
     * @const
     */
    "13": 13,

    /**
     * value: 14
     * @const
     */
    "14": 14,

    /**
     * value: 37
     * @const
     */
    "37": 37,

    /**
     * value: 41
     * @const
     */
    "41": 41,

    /**
     * value: 42
     * @const
     */
    "42": 42,

    /**
     * value: 43
     * @const
     */
    "43": 43,

    /**
     * value: 50
     * @const
     */
    "50": 50,

    /**
     * value: 55
     * @const
     */
    "55": 55,

    /**
     * value: 61
     * @const
     */
    "61": 61,

    /**
     * value: 70
     * @const
     */
    "70": 70,

    /**
     * value: 74
     * @const
     */
    "74": 74,

    /**
     * value: 81
     * @const
     */
    "81": 81,

    /**
     * value: 82
     * @const
     */
    "82": 82,

    /**
     * value: 87
     * @const
     */
    "87": 87,

    /**
     * value: 89
     * @const
     */
    "89": 89,

    /**
     * value: 90
     * @const
     */
    "90": 90,

    /**
     * value: 94
     * @const
     */
    "94": 94,

    /**
     * value: 95
     * @const
     */
    "95": 95,

    /**
     * value: 96
     * @const
     */
    "96": 96,

    /**
     * value: 97
     * @const
     */
    "97": 97,

    /**
     * value: 100
     * @const
     */
    "100": 100,

    /**
     * value: 102
     * @const
     */
    "102": 102,

    /**
     * value: 103
     * @const
     */
    "103": 103,

    /**
     * value: 104
     * @const
     */
    "104": 104,

    /**
     * value: 106
     * @const
     */
    "106": 106,

    /**
     * value: 107
     * @const
     */
    "107": 107,

    /**
     * value: 108
     * @const
     */
    "108": 108,

    /**
     * value: 112
     * @const
     */
    "112": 112,

    /**
     * value: 113
     * @const
     */
    "113": 113,

    /**
     * value: 114
     * @const
     */
    "114": 114,

    /**
     * value: 115
     * @const
     */
    "115": 115,

    /**
     * value: 116
     * @const
     */
    "116": 116,

    /**
     * value: 124
     * @const
     */
    "124": 124,

    /**
     * value: 125
     * @const
     */
    "125": 125,

    /**
     * value: 128
     * @const
     */
    "128": 128,

    /**
     * value: 131
     * @const
     */
    "131": 131,

    /**
     * value: 133
     * @const
     */
    "133": 133,

    /**
     * value: 134
     * @const
     */
    "134": 134,

    /**
     * value: 137
     * @const
     */
    "137": 137,

    /**
     * value: 141
     * @const
     */
    "141": 141,

    /**
     * value: 143
     * @const
     */
    "143": 143,

    /**
     * value: 153
     * @const
     */
    "153": 153,

    /**
     * value: 154
     * @const
     */
    "154": 154,

    /**
     * value: 155
     * @const
     */
    "155": 155,

    /**
     * value: 156
     * @const
     */
    "156": 156,

    /**
     * value: 157
     * @const
     */
    "157": 157,

    /**
     * value: 158
     * @const
     */
    "158": 158,

    /**
     * value: 159
     * @const
     */
    "159": 159,

    /**
     * value: 160
     * @const
     */
    "160": 160,

    /**
     * value: 161
     * @const
     */
    "161": 161,

    /**
     * value: 164
     * @const
     */
    "164": 164,

    /**
     * value: 165
     * @const
     */
    "165": 165,

    /**
     * value: 167
     * @const
     */
    "167": 167,

    /**
     * value: 172
     * @const
     */
    "172": 172,

    /**
     * value: 173
     * @const
     */
    "173": 173,

    /**
     * value: 177
     * @const
     */
    "177": 177,

    /**
     * value: 178
     * @const
     */
    "178": 178,

    /**
     * value: 179
     * @const
     */
    "179": 179,

    /**
     * value: 182
     * @const
     */
    "182": 182,

    /**
     * value: 183
     * @const
     */
    "183": 183,

    /**
     * value: 184
     * @const
     */
    "184": 184,

    /**
     * value: 185
     * @const
     */
    "185": 185,

    /**
     * value: 186
     * @const
     */
    "186": 186,

    /**
     * value: 187
     * @const
     */
    "187": 187,

    /**
     * value: 188
     * @const
     */
    "188": 188,

    /**
     * value: 189
     * @const
     */
    "189": 189,

    /**
     * value: 190
     * @const
     */
    "190": 190,

    /**
     * value: 191
     * @const
     */
    "191": 191,

    /**
     * value: 192
     * @const
     */
    "192": 192,

    /**
     * value: 193
     * @const
     */
    "193": 193,

    /**
     * value: 194
     * @const
     */
    "194": 194,

    /**
     * value: 197
     * @const
     */
    "197": 197,

    /**
     * value: 198
     * @const
     */
    "198": 198,

    /**
     * value: 199
     * @const
     */
    "199": 199,

    /**
     * value: 204
     * @const
     */
    "204": 204,

    /**
     * value: 205
     * @const
     */
    "205": 205,

    /**
     * value: 240
     * @const
     */
    "240": 240,

    /**
     * value: 241
     * @const
     */
    "241": 241,

    /**
     * value: 242
     * @const
     */
    "242": 242,

    /**
     * value: 245
     * @const
     */
    "245": 245,

    /**
     * value: 246
     * @const
     */
    "246": 246,

    /**
     * value: 247
     * @const
     */
    "247": 247,

    /**
     * value: 248
     * @const
     */
    "248": 248,

    /**
     * value: 249
     * @const
     */
    "249": 249,

    /**
     * value: 250
     * @const
     */
    "250": 250,

    /**
     * value: 251
     * @const
     */
    "251": 251,

    /**
     * value: 252
     * @const
     */
    "252": 252,

    /**
     * value: 253
     * @const
     */
    "253": 253,

    /**
     * value: 254
     * @const
     */
    "254": 254,

    /**
     * value: 255
     * @const
     */
    "255": 255,

    /**
     * value: 256
     * @const
     */
    "256": 256,

    /**
     * value: 257
     * @const
     */
    "257": 257,

    /**
     * value: 258
     * @const
     */
    "258": 258,

    /**
     * value: 259
     * @const
     */
    "259": 259,

    /**
     * value: 260
     * @const
     */
    "260": 260,

    /**
     * value: 261
     * @const
     */
    "261": 261,

    /**
     * value: 262
     * @const
     */
    "262": 262,

    /**
     * value: 263
     * @const
     */
    "263": 263,

    /**
     * value: 264
     * @const
     */
    "264": 264,

    /**
     * value: 265
     * @const
     */
    "265": 265,

    /**
     * value: 266
     * @const
     */
    "266": 266,

    /**
     * value: 267
     * @const
     */
    "267": 267,

    /**
     * value: 268
     * @const
     */
    "268": 268,

    /**
     * value: 269
     * @const
     */
    "269": 269,

    /**
     * value: 270
     * @const
     */
    "270": 270,

    /**
     * value: 271
     * @const
     */
    "271": 271,

    /**
     * value: 272
     * @const
     */
    "272": 272,

    /**
     * value: 273
     * @const
     */
    "273": 273,

    /**
     * value: 276
     * @const
     */
    "276": 276,

    /**
     * value: 277
     * @const
     */
    "277": 277,

    /**
     * value: 278
     * @const
     */
    "278": 278,

    /**
     * value: 279
     * @const
     */
    "279": 279,

    /**
     * value: 280
     * @const
     */
    "280": 280,

    /**
     * value: 281
     * @const
     */
    "281": 281,

    /**
     * value: 282
     * @const
     */
    "282": 282,

    /**
     * value: 283
     * @const
     */
    "283": 283,

    /**
     * value: 284
     * @const
     */
    "284": 284,

    /**
     * value: 285
     * @const
     */
    "285": 285,

    /**
     * value: 286
     * @const
     */
    "286": 286,

    /**
     * value: 287
     * @const
     */
    "287": 287,

    /**
     * value: 289
     * @const
     */
    "289": 289,

    /**
     * value: 290
     * @const
     */
    "290": 290,

    /**
     * value: 291
     * @const
     */
    "291": 291
};



export default InlineResponse2001MediaList;

