/**
 * lodgea-js
 * LODGEA SDK for javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse2001Geo from './InlineResponse2001Geo';
import InlineResponse2003PropertyAwardList from './InlineResponse2003PropertyAwardList';
import InlineResponse2003PropertyCancellationGracePeriod from './InlineResponse2003PropertyCancellationGracePeriod';
import InlineResponse2003PropertyContactList from './InlineResponse2003PropertyContactList';
import InlineResponse2003PropertyFacilityInfo from './InlineResponse2003PropertyFacilityInfo';
import InlineResponse2003PropertyGuestInfo from './InlineResponse2003PropertyGuestInfo';
import InlineResponse2003PropertyMediaList from './InlineResponse2003PropertyMediaList';
import InlineResponse2003PropertyPolicyList from './InlineResponse2003PropertyPolicyList';
import InlineResponse2003PropertyPropertyInfo from './InlineResponse2003PropertyPropertyInfo';
import InlineResponse2003PropertyRecordCreated from './InlineResponse2003PropertyRecordCreated';
import InlineResponse2003PropertyRecordModified from './InlineResponse2003PropertyRecordModified';
import InlineResponse2003PropertyServiceList from './InlineResponse2003PropertyServiceList';

/**
 * The InlineResponse2003Property model module.
 * @module com.lodgea/com.lodgea.model/InlineResponse2003Property
 * @version 1.2.0
 */
class InlineResponse2003Property {
    /**
     * Constructs a new <code>InlineResponse2003Property</code>.
     * An object containing all available base data for the requested property.
     * @alias module:com.lodgea/com.lodgea.model/InlineResponse2003Property
     * @param code {String} The properties unique identifier.
     * @param name {String} The properties name.
     * @param recordCreated {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyRecordCreated} 
     * @param recordModified {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyRecordModified} 
     * @param propertyInfo {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyPropertyInfo} 
     * @param awardList {Array.<module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyAwardList>} A list of the ratings available for this property.
     * @param contactList {Array.<module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyContactList>} A contact with a profile type and a list of addresses
     * @param mediaList {Array.<module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyMediaList>} A list of media objects for the property.
     * @param published {Boolean} Indicates whether the policy has been published or not.
     * @param policyList {Array.<module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyPolicyList>} A list of policies associated with the property.
     * @param serviceList {Array.<module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyServiceList>} A list of objects each describing an available service, its pricing and its availability.
     */
    constructor(code, name, recordCreated, recordModified, propertyInfo, awardList, contactList, mediaList, published, policyList, serviceList) { 
        
        InlineResponse2003Property.initialize(this, code, name, recordCreated, recordModified, propertyInfo, awardList, contactList, mediaList, published, policyList, serviceList);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, name, recordCreated, recordModified, propertyInfo, awardList, contactList, mediaList, published, policyList, serviceList) { 
        obj['code'] = code;
        obj['name'] = name;
        obj['recordCreated'] = recordCreated;
        obj['recordModified'] = recordModified;
        obj['propertyInfo'] = propertyInfo;
        obj['awardList'] = awardList;
        obj['contactList'] = contactList;
        obj['mediaList'] = mediaList;
        obj['published'] = published;
        obj['policyList'] = policyList;
        obj['serviceList'] = serviceList;
    }

    /**
     * Constructs a <code>InlineResponse2003Property</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.lodgea/com.lodgea.model/InlineResponse2003Property} obj Optional instance to populate.
     * @return {module:com.lodgea/com.lodgea.model/InlineResponse2003Property} The populated <code>InlineResponse2003Property</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2003Property();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('recordCreated')) {
                obj['recordCreated'] = InlineResponse2003PropertyRecordCreated.constructFromObject(data['recordCreated']);
            }
            if (data.hasOwnProperty('recordModified')) {
                obj['recordModified'] = InlineResponse2003PropertyRecordModified.constructFromObject(data['recordModified']);
            }
            if (data.hasOwnProperty('propertyInfo')) {
                obj['propertyInfo'] = InlineResponse2003PropertyPropertyInfo.constructFromObject(data['propertyInfo']);
            }
            if (data.hasOwnProperty('guestInfo')) {
                obj['guestInfo'] = InlineResponse2003PropertyGuestInfo.constructFromObject(data['guestInfo']);
            }
            if (data.hasOwnProperty('awardList')) {
                obj['awardList'] = ApiClient.convertToType(data['awardList'], [InlineResponse2003PropertyAwardList]);
            }
            if (data.hasOwnProperty('contactList')) {
                obj['contactList'] = ApiClient.convertToType(data['contactList'], [InlineResponse2003PropertyContactList]);
            }
            if (data.hasOwnProperty('facilityInfo')) {
                obj['facilityInfo'] = InlineResponse2003PropertyFacilityInfo.constructFromObject(data['facilityInfo']);
            }
            if (data.hasOwnProperty('mediaList')) {
                obj['mediaList'] = ApiClient.convertToType(data['mediaList'], [InlineResponse2003PropertyMediaList]);
            }
            if (data.hasOwnProperty('geo')) {
                obj['geo'] = ApiClient.convertToType(data['geo'], {'String': InlineResponse2001Geo});
            }
            if (data.hasOwnProperty('published')) {
                obj['published'] = ApiClient.convertToType(data['published'], 'Boolean');
            }
            if (data.hasOwnProperty('policyList')) {
                obj['policyList'] = ApiClient.convertToType(data['policyList'], [InlineResponse2003PropertyPolicyList]);
            }
            if (data.hasOwnProperty('uri')) {
                obj['uri'] = ApiClient.convertToType(data['uri'], 'String');
            }
            if (data.hasOwnProperty('cancellationGracePeriod')) {
                obj['cancellationGracePeriod'] = InlineResponse2003PropertyCancellationGracePeriod.constructFromObject(data['cancellationGracePeriod']);
            }
            if (data.hasOwnProperty('serviceList')) {
                obj['serviceList'] = ApiClient.convertToType(data['serviceList'], [InlineResponse2003PropertyServiceList]);
            }
        }
        return obj;
    }


}

/**
 * The properties unique identifier.
 * @member {String} code
 */
InlineResponse2003Property.prototype['code'] = undefined;

/**
 * The properties name.
 * @member {String} name
 */
InlineResponse2003Property.prototype['name'] = undefined;

/**
 * @member {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyRecordCreated} recordCreated
 */
InlineResponse2003Property.prototype['recordCreated'] = undefined;

/**
 * @member {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyRecordModified} recordModified
 */
InlineResponse2003Property.prototype['recordModified'] = undefined;

/**
 * @member {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyPropertyInfo} propertyInfo
 */
InlineResponse2003Property.prototype['propertyInfo'] = undefined;

/**
 * @member {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyGuestInfo} guestInfo
 */
InlineResponse2003Property.prototype['guestInfo'] = undefined;

/**
 * A list of the ratings available for this property.
 * @member {Array.<module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyAwardList>} awardList
 */
InlineResponse2003Property.prototype['awardList'] = undefined;

/**
 * A contact with a profile type and a list of addresses
 * @member {Array.<module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyContactList>} contactList
 */
InlineResponse2003Property.prototype['contactList'] = undefined;

/**
 * @member {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyFacilityInfo} facilityInfo
 */
InlineResponse2003Property.prototype['facilityInfo'] = undefined;

/**
 * A list of media objects for the property.
 * @member {Array.<module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyMediaList>} mediaList
 */
InlineResponse2003Property.prototype['mediaList'] = undefined;

/**
 * An object containing language codes as keys and objects describing the properties geographical location as values.
 * @member {Object.<String, module:com.lodgea/com.lodgea.model/InlineResponse2001Geo>} geo
 */
InlineResponse2003Property.prototype['geo'] = undefined;

/**
 * Indicates whether the policy has been published or not.
 * @member {Boolean} published
 */
InlineResponse2003Property.prototype['published'] = undefined;

/**
 * A list of policies associated with the property.
 * @member {Array.<module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyPolicyList>} policyList
 */
InlineResponse2003Property.prototype['policyList'] = undefined;

/**
 * A unique identifier for the accommodation.
 * @member {String} uri
 */
InlineResponse2003Property.prototype['uri'] = undefined;

/**
 * @member {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyCancellationGracePeriod} cancellationGracePeriod
 */
InlineResponse2003Property.prototype['cancellationGracePeriod'] = undefined;

/**
 * A list of objects each describing an available service, its pricing and its availability.
 * @member {Array.<module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyServiceList>} serviceList
 */
InlineResponse2003Property.prototype['serviceList'] = undefined;






export default InlineResponse2003Property;

