/**
 * lodgea-js
 * LODGEA SDK for javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2003PropertyGuaranteePolicy model module.
 * @module com.lodgea/com.lodgea.model/InlineResponse2003PropertyGuaranteePolicy
 * @version 1.2.0
 */
class InlineResponse2003PropertyGuaranteePolicy {
    /**
     * Constructs a new <code>InlineResponse2003PropertyGuaranteePolicy</code>.
     * Defines the guarantee amount that has to be paid to the property.
     * @alias module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyGuaranteePolicy
     * @param percentAfterReservation {Number} Percentage of refund after reservation.
     * @param nightsAfterReservation {Number} Number of nights after reservation.
     * @param deadlineDays {Number} Deadline in days.
     * @param deadlineHours {Number} Deadline in hours.
     * @param percentAfterDeadline {Number} Percentage of refund after deadline.
     * @param nightsAfterDeadline {Number} Number of nights after deadline.
     * @param noShowPolicy {String} No-show policy
     */
    constructor(percentAfterReservation, nightsAfterReservation, deadlineDays, deadlineHours, percentAfterDeadline, nightsAfterDeadline, noShowPolicy) { 
        
        InlineResponse2003PropertyGuaranteePolicy.initialize(this, percentAfterReservation, nightsAfterReservation, deadlineDays, deadlineHours, percentAfterDeadline, nightsAfterDeadline, noShowPolicy);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, percentAfterReservation, nightsAfterReservation, deadlineDays, deadlineHours, percentAfterDeadline, nightsAfterDeadline, noShowPolicy) { 
        obj['percentAfterReservation'] = percentAfterReservation;
        obj['nightsAfterReservation'] = nightsAfterReservation;
        obj['deadlineDays'] = deadlineDays;
        obj['deadlineHours'] = deadlineHours;
        obj['percentAfterDeadline'] = percentAfterDeadline;
        obj['nightsAfterDeadline'] = nightsAfterDeadline;
        obj['noShowPolicy'] = noShowPolicy;
    }

    /**
     * Constructs a <code>InlineResponse2003PropertyGuaranteePolicy</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyGuaranteePolicy} obj Optional instance to populate.
     * @return {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyGuaranteePolicy} The populated <code>InlineResponse2003PropertyGuaranteePolicy</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2003PropertyGuaranteePolicy();

            if (data.hasOwnProperty('percentAfterReservation')) {
                obj['percentAfterReservation'] = ApiClient.convertToType(data['percentAfterReservation'], 'Number');
            }
            if (data.hasOwnProperty('nightsAfterReservation')) {
                obj['nightsAfterReservation'] = ApiClient.convertToType(data['nightsAfterReservation'], 'Number');
            }
            if (data.hasOwnProperty('deadlineDays')) {
                obj['deadlineDays'] = ApiClient.convertToType(data['deadlineDays'], 'Number');
            }
            if (data.hasOwnProperty('deadlineHours')) {
                obj['deadlineHours'] = ApiClient.convertToType(data['deadlineHours'], 'Number');
            }
            if (data.hasOwnProperty('percentAfterDeadline')) {
                obj['percentAfterDeadline'] = ApiClient.convertToType(data['percentAfterDeadline'], 'Number');
            }
            if (data.hasOwnProperty('nightsAfterDeadline')) {
                obj['nightsAfterDeadline'] = ApiClient.convertToType(data['nightsAfterDeadline'], 'Number');
            }
            if (data.hasOwnProperty('noShowPolicy')) {
                obj['noShowPolicy'] = ApiClient.convertToType(data['noShowPolicy'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Percentage of refund after reservation.
 * @member {Number} percentAfterReservation
 */
InlineResponse2003PropertyGuaranteePolicy.prototype['percentAfterReservation'] = undefined;

/**
 * Number of nights after reservation.
 * @member {Number} nightsAfterReservation
 */
InlineResponse2003PropertyGuaranteePolicy.prototype['nightsAfterReservation'] = undefined;

/**
 * Deadline in days.
 * @member {Number} deadlineDays
 */
InlineResponse2003PropertyGuaranteePolicy.prototype['deadlineDays'] = undefined;

/**
 * Deadline in hours.
 * @member {Number} deadlineHours
 */
InlineResponse2003PropertyGuaranteePolicy.prototype['deadlineHours'] = undefined;

/**
 * Percentage of refund after deadline.
 * @member {Number} percentAfterDeadline
 */
InlineResponse2003PropertyGuaranteePolicy.prototype['percentAfterDeadline'] = undefined;

/**
 * Number of nights after deadline.
 * @member {Number} nightsAfterDeadline
 */
InlineResponse2003PropertyGuaranteePolicy.prototype['nightsAfterDeadline'] = undefined;

/**
 * No-show policy
 * @member {String} noShowPolicy
 */
InlineResponse2003PropertyGuaranteePolicy.prototype['noShowPolicy'] = undefined;






export default InlineResponse2003PropertyGuaranteePolicy;

