/**
 * lodgea-js
 * LODGEA SDK for javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse2003PropertyAddressList from './InlineResponse2003PropertyAddressList';

/**
 * The InlineResponse2003PropertyContactList model module.
 * @module com.lodgea/com.lodgea.model/InlineResponse2003PropertyContactList
 * @version 1.2.0
 */
class InlineResponse2003PropertyContactList {
    /**
     * Constructs a new <code>InlineResponse2003PropertyContactList</code>.
     * @alias module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyContactList
     * @param profileType {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyContactList.ProfileTypeEnum} The type of profile this contact belongs to.
     * @param addressList {Array.<module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyAddressList>} A list of addresses for this contact
     */
    constructor(profileType, addressList) { 
        
        InlineResponse2003PropertyContactList.initialize(this, profileType, addressList);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, profileType, addressList) { 
        obj['profileType'] = profileType;
        obj['addressList'] = addressList;
    }

    /**
     * Constructs a <code>InlineResponse2003PropertyContactList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyContactList} obj Optional instance to populate.
     * @return {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyContactList} The populated <code>InlineResponse2003PropertyContactList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2003PropertyContactList();

            if (data.hasOwnProperty('profileType')) {
                obj['profileType'] = ApiClient.convertToType(data['profileType'], 'String');
            }
            if (data.hasOwnProperty('addressList')) {
                obj['addressList'] = ApiClient.convertToType(data['addressList'], [InlineResponse2003PropertyAddressList]);
            }
        }
        return obj;
    }


}

/**
 * The type of profile this contact belongs to.
 * @member {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyContactList.ProfileTypeEnum} profileType
 */
InlineResponse2003PropertyContactList.prototype['profileType'] = undefined;

/**
 * A list of addresses for this contact
 * @member {Array.<module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyAddressList>} addressList
 */
InlineResponse2003PropertyContactList.prototype['addressList'] = undefined;





/**
 * Allowed values for the <code>profileType</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse2003PropertyContactList['ProfileTypeEnum'] = {

    /**
     * value: "general"
     * @const
     */
    "general": "general",

    /**
     * value: "contract"
     * @const
     */
    "contract": "contract",

    /**
     * value: "reservations"
     * @const
     */
    "reservations": "reservations",

    /**
     * value: "invoices"
     * @const
     */
    "invoices": "invoices",

    /**
     * value: "availability"
     * @const
     */
    "availability": "availability",

    /**
     * value: "site_content"
     * @const
     */
    "site_content": "site_content",

    /**
     * value: "parity"
     * @const
     */
    "parity": "parity",

    /**
     * value: "requests"
     * @const
     */
    "requests": "requests",

    /**
     * value: "central_reservations"
     * @const
     */
    "central_reservations": "central_reservations",

    /**
     * value: "physicallocation"
     * @const
     */
    "physicallocation": "physicallocation"
};



export default InlineResponse2003PropertyContactList;

