/**
 * lodgea-js
 * LODGEA SDK for javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner model module.
 * @module com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner
 * @version 1.1.0
 */
class PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner {
    /**
     * Constructs a new <code>PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner</code>.
     * @alias module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner
     * @param start {Number} The start time of operation in milliseconds.
     * @param end {Number} The end time of operation in milliseconds.
     * @param monday {Boolean} Indicates whether the operation is open on Monday.
     * @param tuesday {Boolean} Indicates whether the operation is open on Tuesday.
     * @param wednesday {Boolean} Indicates whether the operation is open on Wednesday.
     * @param thursday {Boolean} Indicates whether the operation is open on Thursday.
     * @param friday {Boolean} Indicates whether the operation is open on Friday.
     * @param saturday {Boolean} Indicates whether the operation is open on Saturday.
     * @param sunday {Boolean} Indicates whether the operation is open on Sunday.
     */
    constructor(start, end, monday, tuesday, wednesday, thursday, friday, saturday, sunday) { 
        
        PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner.initialize(this, start, end, monday, tuesday, wednesday, thursday, friday, saturday, sunday);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, start, end, monday, tuesday, wednesday, thursday, friday, saturday, sunday) { 
        obj['start'] = start;
        obj['end'] = end;
        obj['monday'] = monday;
        obj['tuesday'] = tuesday;
        obj['wednesday'] = wednesday;
        obj['thursday'] = thursday;
        obj['friday'] = friday;
        obj['saturday'] = saturday;
        obj['sunday'] = sunday;
    }

    /**
     * Constructs a <code>PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner} obj Optional instance to populate.
     * @return {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner} The populated <code>PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner();

            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], 'Number');
            }
            if (data.hasOwnProperty('end')) {
                obj['end'] = ApiClient.convertToType(data['end'], 'Number');
            }
            if (data.hasOwnProperty('monday')) {
                obj['monday'] = ApiClient.convertToType(data['monday'], 'Boolean');
            }
            if (data.hasOwnProperty('tuesday')) {
                obj['tuesday'] = ApiClient.convertToType(data['tuesday'], 'Boolean');
            }
            if (data.hasOwnProperty('wednesday')) {
                obj['wednesday'] = ApiClient.convertToType(data['wednesday'], 'Boolean');
            }
            if (data.hasOwnProperty('thursday')) {
                obj['thursday'] = ApiClient.convertToType(data['thursday'], 'Boolean');
            }
            if (data.hasOwnProperty('friday')) {
                obj['friday'] = ApiClient.convertToType(data['friday'], 'Boolean');
            }
            if (data.hasOwnProperty('saturday')) {
                obj['saturday'] = ApiClient.convertToType(data['saturday'], 'Boolean');
            }
            if (data.hasOwnProperty('sunday')) {
                obj['sunday'] = ApiClient.convertToType(data['sunday'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner.RequiredProperties = ["start", "end", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"];

/**
 * The start time of operation in milliseconds.
 * @member {Number} start
 */
PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner.prototype['start'] = undefined;

/**
 * The end time of operation in milliseconds.
 * @member {Number} end
 */
PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner.prototype['end'] = undefined;

/**
 * Indicates whether the operation is open on Monday.
 * @member {Boolean} monday
 */
PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner.prototype['monday'] = undefined;

/**
 * Indicates whether the operation is open on Tuesday.
 * @member {Boolean} tuesday
 */
PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner.prototype['tuesday'] = undefined;

/**
 * Indicates whether the operation is open on Wednesday.
 * @member {Boolean} wednesday
 */
PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner.prototype['wednesday'] = undefined;

/**
 * Indicates whether the operation is open on Thursday.
 * @member {Boolean} thursday
 */
PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner.prototype['thursday'] = undefined;

/**
 * Indicates whether the operation is open on Friday.
 * @member {Boolean} friday
 */
PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner.prototype['friday'] = undefined;

/**
 * Indicates whether the operation is open on Saturday.
 * @member {Boolean} saturday
 */
PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner.prototype['saturday'] = undefined;

/**
 * Indicates whether the operation is open on Sunday.
 * @member {Boolean} sunday
 */
PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner.prototype['sunday'] = undefined;






export default PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner;

