/**
 * lodgea-js
 * LODGEA SDK for Javascript. Check out https://lodgea.redoc.ly for more information.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PropertyGet model module.
 * @module com.lodgea/com.lodgea.model/PropertyGet
 * @version 1.0.0
 */
class PropertyGet {
    /**
     * Constructs a new <code>PropertyGet</code>.
     * @alias module:com.lodgea/com.lodgea.model/PropertyGet
     */
    constructor() { 
        
        PropertyGet.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PropertyGet</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.lodgea/com.lodgea.model/PropertyGet} obj Optional instance to populate.
     * @return {module:com.lodgea/com.lodgea.model/PropertyGet} The populated <code>PropertyGet</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PropertyGet();

            if (data.hasOwnProperty('propertyId')) {
                obj['propertyId'] = ApiClient.convertToType(data['propertyId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} propertyId
 */
PropertyGet.prototype['propertyId'] = undefined;






export default PropertyGet;

