/**
 * lodgea-js
 * LODGEA SDK for javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod model module.
 * @module com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod
 * @version 1.1.0
 */
class PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod {
    /**
     * Constructs a new <code>PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod</code>.
     * An object describing the cancellation grace periods.
     * @alias module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod
     * @param hoursAfterBooking {Number} The number of hours after booking that the cancellation grace period starts.
     * @param weeksBeforeCheckIn {Number} The number of weeks before check-in that the cancellation grace period starts.
     */
    constructor(hoursAfterBooking, weeksBeforeCheckIn) { 
        
        PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod.initialize(this, hoursAfterBooking, weeksBeforeCheckIn);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, hoursAfterBooking, weeksBeforeCheckIn) { 
        obj['hoursAfterBooking'] = hoursAfterBooking;
        obj['weeksBeforeCheckIn'] = weeksBeforeCheckIn;
    }

    /**
     * Constructs a <code>PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod} obj Optional instance to populate.
     * @return {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod} The populated <code>PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod();

            if (data.hasOwnProperty('hoursAfterBooking')) {
                obj['hoursAfterBooking'] = ApiClient.convertToType(data['hoursAfterBooking'], 'Number');
            }
            if (data.hasOwnProperty('weeksBeforeCheckIn')) {
                obj['weeksBeforeCheckIn'] = ApiClient.convertToType(data['weeksBeforeCheckIn'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod.RequiredProperties = ["hoursAfterBooking", "weeksBeforeCheckIn"];

/**
 * The number of hours after booking that the cancellation grace period starts.
 * @member {Number} hoursAfterBooking
 */
PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod.prototype['hoursAfterBooking'] = undefined;

/**
 * The number of weeks before check-in that the cancellation grace period starts.
 * @member {Number} weeksBeforeCheckIn
 */
PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod.prototype['weeksBeforeCheckIn'] = undefined;






export default PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod;

