/**
 * lodgea-js
 * LODGEA SDK for Javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PropertiesPropertyIdGet200ResponsePropertyAwardListInner model module.
 * @module com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyAwardListInner
 * @version 1.1.0
 */
class PropertiesPropertyIdGet200ResponsePropertyAwardListInner {
    /**
     * Constructs a new <code>PropertiesPropertyIdGet200ResponsePropertyAwardListInner</code>.
     * @alias module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyAwardListInner
     * @param provider {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyAwardListInner.ProviderEnum} The source of this rating. Currently only <code>star-rating</code> is possible.
     * @param rating {Number} The value of this rating
     */
    constructor(provider, rating) { 
        
        PropertiesPropertyIdGet200ResponsePropertyAwardListInner.initialize(this, provider, rating);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, provider, rating) { 
        obj['provider'] = provider;
        obj['rating'] = rating;
    }

    /**
     * Constructs a <code>PropertiesPropertyIdGet200ResponsePropertyAwardListInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyAwardListInner} obj Optional instance to populate.
     * @return {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyAwardListInner} The populated <code>PropertiesPropertyIdGet200ResponsePropertyAwardListInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PropertiesPropertyIdGet200ResponsePropertyAwardListInner();

            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
            if (data.hasOwnProperty('rating')) {
                obj['rating'] = ApiClient.convertToType(data['rating'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The source of this rating. Currently only <code>star-rating</code> is possible.
 * @member {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyAwardListInner.ProviderEnum} provider
 */
PropertiesPropertyIdGet200ResponsePropertyAwardListInner.prototype['provider'] = undefined;

/**
 * The value of this rating
 * @member {Number} rating
 */
PropertiesPropertyIdGet200ResponsePropertyAwardListInner.prototype['rating'] = undefined;





/**
 * Allowed values for the <code>provider</code> property.
 * @enum {String}
 * @readonly
 */
PropertiesPropertyIdGet200ResponsePropertyAwardListInner['ProviderEnum'] = {

    /**
     * value: "star-rating"
     * @const
     */
    "star-rating": "star-rating"
};



export default PropertiesPropertyIdGet200ResponsePropertyAwardListInner;

