/**
 * lodgea-js
 * LODGEA SDK for javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner model module.
 * @module com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner
 * @version 1.1.5
 */
class PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner {
    /**
     * Constructs a new <code>PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner</code>.
     * @alias module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner
     * @param addressLine {String} The first line of the address for this contact
     * @param cityName {String} The city of this contact
     * @param postalCode {String} The postal code of this contact
     */
    constructor(addressLine, cityName, postalCode) { 
        
        PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner.initialize(this, addressLine, cityName, postalCode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, addressLine, cityName, postalCode) { 
        obj['addressLine'] = addressLine;
        obj['cityName'] = cityName;
        obj['postalCode'] = postalCode;
    }

    /**
     * Constructs a <code>PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner} obj Optional instance to populate.
     * @return {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner} The populated <code>PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner();

            if (data.hasOwnProperty('addressLine')) {
                obj['addressLine'] = ApiClient.convertToType(data['addressLine'], 'String');
            }
            if (data.hasOwnProperty('propertyName')) {
                obj['propertyName'] = ApiClient.convertToType(data['propertyName'], 'String');
            }
            if (data.hasOwnProperty('cityName')) {
                obj['cityName'] = ApiClient.convertToType(data['cityName'], 'String');
            }
            if (data.hasOwnProperty('postalCode')) {
                obj['postalCode'] = ApiClient.convertToType(data['postalCode'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('countryCode')) {
                obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['addressLine'] && !(typeof data['addressLine'] === 'string' || data['addressLine'] instanceof String)) {
            throw new Error("Expected the field `addressLine` to be a primitive type in the JSON string but got " + data['addressLine']);
        }
        // ensure the json data is a string
        if (data['propertyName'] && !(typeof data['propertyName'] === 'string' || data['propertyName'] instanceof String)) {
            throw new Error("Expected the field `propertyName` to be a primitive type in the JSON string but got " + data['propertyName']);
        }
        // ensure the json data is a string
        if (data['cityName'] && !(typeof data['cityName'] === 'string' || data['cityName'] instanceof String)) {
            throw new Error("Expected the field `cityName` to be a primitive type in the JSON string but got " + data['cityName']);
        }
        // ensure the json data is a string
        if (data['postalCode'] && !(typeof data['postalCode'] === 'string' || data['postalCode'] instanceof String)) {
            throw new Error("Expected the field `postalCode` to be a primitive type in the JSON string but got " + data['postalCode']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }
        // ensure the json data is a string
        if (data['countryCode'] && !(typeof data['countryCode'] === 'string' || data['countryCode'] instanceof String)) {
            throw new Error("Expected the field `countryCode` to be a primitive type in the JSON string but got " + data['countryCode']);
        }

        return true;
    }


}

PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner.RequiredProperties = ["addressLine", "cityName", "postalCode"];

/**
 * The first line of the address for this contact
 * @member {String} addressLine
 */
PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner.prototype['addressLine'] = undefined;

/**
 * The name of the property for this contact
 * @member {String} propertyName
 */
PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner.prototype['propertyName'] = undefined;

/**
 * The city of this contact
 * @member {String} cityName
 */
PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner.prototype['cityName'] = undefined;

/**
 * The postal code of this contact
 * @member {String} postalCode
 */
PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner.prototype['postalCode'] = undefined;

/**
 * The state/region of this contact
 * @member {String} state
 */
PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner.prototype['state'] = undefined;

/**
 * The country code of this contact
 * @member {String} countryCode
 */
PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner.prototype['countryCode'] = undefined;






export default PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner;

