/**
 * lodgea-js
 * LODGEA SDK for Javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList from './V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList';

/**
 * The V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner model module.
 * @module com.lodgea/com.lodgea.model/V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner
 * @version 1.0.2
 */
class V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner {
    /**
     * Constructs a new <code>V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner</code>.
     * @alias module:com.lodgea/com.lodgea.model/V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner
     */
    constructor() { 
        
        V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.lodgea/com.lodgea.model/V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner} obj Optional instance to populate.
     * @return {module:com.lodgea/com.lodgea.model/V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner} The populated <code>V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner();

            if (data.hasOwnProperty('dateTime')) {
                obj['dateTime'] = ApiClient.convertToType(data['dateTime'], 'Number');
            }
            if (data.hasOwnProperty('occupancy')) {
                obj['occupancy'] = ApiClient.convertToType(data['occupancy'], 'Number');
            }
            if (data.hasOwnProperty('priceList')) {
                obj['priceList'] = V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.constructFromObject(data['priceList']);
            }
            if (data.hasOwnProperty('currencyCode')) {
                obj['currencyCode'] = ApiClient.convertToType(data['currencyCode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} dateTime
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner.prototype['dateTime'] = undefined;

/**
 * @member {Number} occupancy
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner.prototype['occupancy'] = undefined;

/**
 * @member {module:com.lodgea/com.lodgea.model/V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList} priceList
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner.prototype['priceList'] = undefined;

/**
 * @member {String} currencyCode
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner.prototype['currencyCode'] = undefined;






export default V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner;

