/**
 * lodgea-js
 * LODGEA SDK for Javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList model module.
 * @module com.lodgea/com.lodgea.model/V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList
 * @version 1.0.2
 */
class V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList {
    /**
     * Constructs a new <code>V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList</code>.
     * @alias module:com.lodgea/com.lodgea.model/V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList
     */
    constructor() { 
        
        V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.lodgea/com.lodgea.model/V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList} obj Optional instance to populate.
     * @return {module:com.lodgea/com.lodgea.model/V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList} The populated <code>V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();

            if (data.hasOwnProperty('3')) {
                obj['3'] = ApiClient.convertToType(data['3'], 'Number');
            }
            if (data.hasOwnProperty('4')) {
                obj['4'] = ApiClient.convertToType(data['4'], 'Number');
            }
            if (data.hasOwnProperty('5')) {
                obj['5'] = ApiClient.convertToType(data['5'], 'Number');
            }
            if (data.hasOwnProperty('6')) {
                obj['6'] = ApiClient.convertToType(data['6'], 'Number');
            }
            if (data.hasOwnProperty('7')) {
                obj['7'] = ApiClient.convertToType(data['7'], 'Number');
            }
            if (data.hasOwnProperty('8')) {
                obj['8'] = ApiClient.convertToType(data['8'], 'Number');
            }
            if (data.hasOwnProperty('9')) {
                obj['9'] = ApiClient.convertToType(data['9'], 'Number');
            }
            if (data.hasOwnProperty('10')) {
                obj['10'] = ApiClient.convertToType(data['10'], 'Number');
            }
            if (data.hasOwnProperty('11')) {
                obj['11'] = ApiClient.convertToType(data['11'], 'Number');
            }
            if (data.hasOwnProperty('12')) {
                obj['12'] = ApiClient.convertToType(data['12'], 'Number');
            }
            if (data.hasOwnProperty('13')) {
                obj['13'] = ApiClient.convertToType(data['13'], 'Number');
            }
            if (data.hasOwnProperty('14')) {
                obj['14'] = ApiClient.convertToType(data['14'], 'Number');
            }
            if (data.hasOwnProperty('15')) {
                obj['15'] = ApiClient.convertToType(data['15'], 'Number');
            }
            if (data.hasOwnProperty('16')) {
                obj['16'] = ApiClient.convertToType(data['16'], 'Number');
            }
            if (data.hasOwnProperty('17')) {
                obj['17'] = ApiClient.convertToType(data['17'], 'Number');
            }
            if (data.hasOwnProperty('18')) {
                obj['18'] = ApiClient.convertToType(data['18'], 'Number');
            }
            if (data.hasOwnProperty('19')) {
                obj['19'] = ApiClient.convertToType(data['19'], 'Number');
            }
            if (data.hasOwnProperty('20')) {
                obj['20'] = ApiClient.convertToType(data['20'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} 3
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.prototype['3'] = undefined;

/**
 * @member {Number} 4
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.prototype['4'] = undefined;

/**
 * @member {Number} 5
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.prototype['5'] = undefined;

/**
 * @member {Number} 6
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.prototype['6'] = undefined;

/**
 * @member {Number} 7
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.prototype['7'] = undefined;

/**
 * @member {Number} 8
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.prototype['8'] = undefined;

/**
 * @member {Number} 9
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.prototype['9'] = undefined;

/**
 * @member {Number} 10
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.prototype['10'] = undefined;

/**
 * @member {Number} 11
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.prototype['11'] = undefined;

/**
 * @member {Number} 12
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.prototype['12'] = undefined;

/**
 * @member {Number} 13
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.prototype['13'] = undefined;

/**
 * @member {Number} 14
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.prototype['14'] = undefined;

/**
 * @member {Number} 15
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.prototype['15'] = undefined;

/**
 * @member {Number} 16
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.prototype['16'] = undefined;

/**
 * @member {Number} 17
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.prototype['17'] = undefined;

/**
 * @member {Number} 18
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.prototype['18'] = undefined;

/**
 * @member {Number} 19
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.prototype['19'] = undefined;

/**
 * @member {Number} 20
 */
V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList.prototype['20'] = undefined;






export default V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList;

