/**
 * lodgea-js
 * LODGEA SDK for Javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1AvailabilityGetPost200ResponseRoomTypeListInner model module.
 * @module com.lodgea/com.lodgea.model/V1AvailabilityGetPost200ResponseRoomTypeListInner
 * @version 1.0.2
 */
class V1AvailabilityGetPost200ResponseRoomTypeListInner {
    /**
     * Constructs a new <code>V1AvailabilityGetPost200ResponseRoomTypeListInner</code>.
     * @alias module:com.lodgea/com.lodgea.model/V1AvailabilityGetPost200ResponseRoomTypeListInner
     */
    constructor() { 
        
        V1AvailabilityGetPost200ResponseRoomTypeListInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1AvailabilityGetPost200ResponseRoomTypeListInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.lodgea/com.lodgea.model/V1AvailabilityGetPost200ResponseRoomTypeListInner} obj Optional instance to populate.
     * @return {module:com.lodgea/com.lodgea.model/V1AvailabilityGetPost200ResponseRoomTypeListInner} The populated <code>V1AvailabilityGetPost200ResponseRoomTypeListInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1AvailabilityGetPost200ResponseRoomTypeListInner();

            if (data.hasOwnProperty('typeCode')) {
                obj['typeCode'] = ApiClient.convertToType(data['typeCode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} typeCode
 */
V1AvailabilityGetPost200ResponseRoomTypeListInner.prototype['typeCode'] = undefined;






export default V1AvailabilityGetPost200ResponseRoomTypeListInner;

