/**
 * lodgea-js
 * LODGEA SDK for Javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1PropertyGetPost200ResponsePropertyAwardListInner from './V1PropertyGetPost200ResponsePropertyAwardListInner';
import V1PropertyGetPost200ResponsePropertyCancellationGracePeriod from './V1PropertyGetPost200ResponsePropertyCancellationGracePeriod';
import V1PropertyGetPost200ResponsePropertyContactListInner from './V1PropertyGetPost200ResponsePropertyContactListInner';
import V1PropertyGetPost200ResponsePropertyFacilityInfo from './V1PropertyGetPost200ResponsePropertyFacilityInfo';
import V1PropertyGetPost200ResponsePropertyGeo from './V1PropertyGetPost200ResponsePropertyGeo';
import V1PropertyGetPost200ResponsePropertyGuestInfo from './V1PropertyGetPost200ResponsePropertyGuestInfo';
import V1PropertyGetPost200ResponsePropertyMediaListInner from './V1PropertyGetPost200ResponsePropertyMediaListInner';
import V1PropertyGetPost200ResponsePropertyPolicyListInner from './V1PropertyGetPost200ResponsePropertyPolicyListInner';
import V1PropertyGetPost200ResponsePropertyPropertyInfo from './V1PropertyGetPost200ResponsePropertyPropertyInfo';
import V1PropertyGetPost200ResponsePropertyRecordCreated from './V1PropertyGetPost200ResponsePropertyRecordCreated';
import V1PropertyGetPost200ResponsePropertyRecordModified from './V1PropertyGetPost200ResponsePropertyRecordModified';
import V1PropertyGetPost200ResponsePropertyServiceListInner from './V1PropertyGetPost200ResponsePropertyServiceListInner';
import V1PropertyGetPost200ResponsePropertyTransaction from './V1PropertyGetPost200ResponsePropertyTransaction';

/**
 * The V1PropertyGetPost200ResponseProperty model module.
 * @module com.lodgea/com.lodgea.model/V1PropertyGetPost200ResponseProperty
 * @version 1.0.1
 */
class V1PropertyGetPost200ResponseProperty {
    /**
     * Constructs a new <code>V1PropertyGetPost200ResponseProperty</code>.
     * @alias module:com.lodgea/com.lodgea.model/V1PropertyGetPost200ResponseProperty
     */
    constructor() { 
        
        V1PropertyGetPost200ResponseProperty.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1PropertyGetPost200ResponseProperty</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.lodgea/com.lodgea.model/V1PropertyGetPost200ResponseProperty} obj Optional instance to populate.
     * @return {module:com.lodgea/com.lodgea.model/V1PropertyGetPost200ResponseProperty} The populated <code>V1PropertyGetPost200ResponseProperty</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1PropertyGetPost200ResponseProperty();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('recordCreated')) {
                obj['recordCreated'] = V1PropertyGetPost200ResponsePropertyRecordCreated.constructFromObject(data['recordCreated']);
            }
            if (data.hasOwnProperty('recordModified')) {
                obj['recordModified'] = V1PropertyGetPost200ResponsePropertyRecordModified.constructFromObject(data['recordModified']);
            }
            if (data.hasOwnProperty('propertyInfo')) {
                obj['propertyInfo'] = V1PropertyGetPost200ResponsePropertyPropertyInfo.constructFromObject(data['propertyInfo']);
            }
            if (data.hasOwnProperty('guestInfo')) {
                obj['guestInfo'] = V1PropertyGetPost200ResponsePropertyGuestInfo.constructFromObject(data['guestInfo']);
            }
            if (data.hasOwnProperty('awardList')) {
                obj['awardList'] = ApiClient.convertToType(data['awardList'], [V1PropertyGetPost200ResponsePropertyAwardListInner]);
            }
            if (data.hasOwnProperty('contactList')) {
                obj['contactList'] = ApiClient.convertToType(data['contactList'], [V1PropertyGetPost200ResponsePropertyContactListInner]);
            }
            if (data.hasOwnProperty('facilityInfo')) {
                obj['facilityInfo'] = V1PropertyGetPost200ResponsePropertyFacilityInfo.constructFromObject(data['facilityInfo']);
            }
            if (data.hasOwnProperty('mediaList')) {
                obj['mediaList'] = ApiClient.convertToType(data['mediaList'], [V1PropertyGetPost200ResponsePropertyMediaListInner]);
            }
            if (data.hasOwnProperty('geo')) {
                obj['geo'] = V1PropertyGetPost200ResponsePropertyGeo.constructFromObject(data['geo']);
            }
            if (data.hasOwnProperty('refinementDate')) {
                obj['refinementDate'] = ApiClient.convertToType(data['refinementDate'], 'Number');
            }
            if (data.hasOwnProperty('published')) {
                obj['published'] = ApiClient.convertToType(data['published'], 'Boolean');
            }
            if (data.hasOwnProperty('policyList')) {
                obj['policyList'] = ApiClient.convertToType(data['policyList'], [V1PropertyGetPost200ResponsePropertyPolicyListInner]);
            }
            if (data.hasOwnProperty('uri')) {
                obj['uri'] = ApiClient.convertToType(data['uri'], 'String');
            }
            if (data.hasOwnProperty('transaction')) {
                obj['transaction'] = V1PropertyGetPost200ResponsePropertyTransaction.constructFromObject(data['transaction']);
            }
            if (data.hasOwnProperty('cancellationGracePeriod')) {
                obj['cancellationGracePeriod'] = V1PropertyGetPost200ResponsePropertyCancellationGracePeriod.constructFromObject(data['cancellationGracePeriod']);
            }
            if (data.hasOwnProperty('serviceList')) {
                obj['serviceList'] = ApiClient.convertToType(data['serviceList'], [V1PropertyGetPost200ResponsePropertyServiceListInner]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} code
 */
V1PropertyGetPost200ResponseProperty.prototype['code'] = undefined;

/**
 * @member {String} name
 */
V1PropertyGetPost200ResponseProperty.prototype['name'] = undefined;

/**
 * @member {module:com.lodgea/com.lodgea.model/V1PropertyGetPost200ResponsePropertyRecordCreated} recordCreated
 */
V1PropertyGetPost200ResponseProperty.prototype['recordCreated'] = undefined;

/**
 * @member {module:com.lodgea/com.lodgea.model/V1PropertyGetPost200ResponsePropertyRecordModified} recordModified
 */
V1PropertyGetPost200ResponseProperty.prototype['recordModified'] = undefined;

/**
 * @member {module:com.lodgea/com.lodgea.model/V1PropertyGetPost200ResponsePropertyPropertyInfo} propertyInfo
 */
V1PropertyGetPost200ResponseProperty.prototype['propertyInfo'] = undefined;

/**
 * @member {module:com.lodgea/com.lodgea.model/V1PropertyGetPost200ResponsePropertyGuestInfo} guestInfo
 */
V1PropertyGetPost200ResponseProperty.prototype['guestInfo'] = undefined;

/**
 * @member {Array.<module:com.lodgea/com.lodgea.model/V1PropertyGetPost200ResponsePropertyAwardListInner>} awardList
 */
V1PropertyGetPost200ResponseProperty.prototype['awardList'] = undefined;

/**
 * @member {Array.<module:com.lodgea/com.lodgea.model/V1PropertyGetPost200ResponsePropertyContactListInner>} contactList
 */
V1PropertyGetPost200ResponseProperty.prototype['contactList'] = undefined;

/**
 * @member {module:com.lodgea/com.lodgea.model/V1PropertyGetPost200ResponsePropertyFacilityInfo} facilityInfo
 */
V1PropertyGetPost200ResponseProperty.prototype['facilityInfo'] = undefined;

/**
 * @member {Array.<module:com.lodgea/com.lodgea.model/V1PropertyGetPost200ResponsePropertyMediaListInner>} mediaList
 */
V1PropertyGetPost200ResponseProperty.prototype['mediaList'] = undefined;

/**
 * @member {module:com.lodgea/com.lodgea.model/V1PropertyGetPost200ResponsePropertyGeo} geo
 */
V1PropertyGetPost200ResponseProperty.prototype['geo'] = undefined;

/**
 * @member {Number} refinementDate
 */
V1PropertyGetPost200ResponseProperty.prototype['refinementDate'] = undefined;

/**
 * @member {Boolean} published
 */
V1PropertyGetPost200ResponseProperty.prototype['published'] = undefined;

/**
 * @member {Array.<module:com.lodgea/com.lodgea.model/V1PropertyGetPost200ResponsePropertyPolicyListInner>} policyList
 */
V1PropertyGetPost200ResponseProperty.prototype['policyList'] = undefined;

/**
 * @member {String} uri
 */
V1PropertyGetPost200ResponseProperty.prototype['uri'] = undefined;

/**
 * @member {module:com.lodgea/com.lodgea.model/V1PropertyGetPost200ResponsePropertyTransaction} transaction
 */
V1PropertyGetPost200ResponseProperty.prototype['transaction'] = undefined;

/**
 * @member {module:com.lodgea/com.lodgea.model/V1PropertyGetPost200ResponsePropertyCancellationGracePeriod} cancellationGracePeriod
 */
V1PropertyGetPost200ResponseProperty.prototype['cancellationGracePeriod'] = undefined;

/**
 * @member {Array.<module:com.lodgea/com.lodgea.model/V1PropertyGetPost200ResponsePropertyServiceListInner>} serviceList
 */
V1PropertyGetPost200ResponseProperty.prototype['serviceList'] = undefined;






export default V1PropertyGetPost200ResponseProperty;

