/**
 * lodgea-js
 * LODGEA SDK for javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AvailabilitySearchPost200Response from './com.lodgea.model/AvailabilitySearchPost200Response';
import AvailabilitySearchPostRequest from './com.lodgea.model/AvailabilitySearchPostRequest';
import AvailablePropertiesInner from './com.lodgea.model/AvailablePropertiesInner';
import AvailablePropertiesInner1 from './com.lodgea.model/AvailablePropertiesInner1';
import AvailablePropertiesInner1AttractionListInner from './com.lodgea.model/AvailablePropertiesInner1AttractionListInner';
import AvailablePropertiesInner1AttractionListInnerDistance from './com.lodgea.model/AvailablePropertiesInner1AttractionListInnerDistance';
import AvailablePropertiesInner1Geo from './com.lodgea.model/AvailablePropertiesInner1Geo';
import AvailablePropertiesInner1GeoLocation from './com.lodgea.model/AvailablePropertiesInner1GeoLocation';
import AvailablePropertiesInner1LowestPrice from './com.lodgea.model/AvailablePropertiesInner1LowestPrice';
import AvailablePropertiesInner1MediaListInner from './com.lodgea.model/AvailablePropertiesInner1MediaListInner';
import LocationSearchPost200Response from './com.lodgea.model/LocationSearchPost200Response';
import LocationSearchPost400Response from './com.lodgea.model/LocationSearchPost400Response';
import LocationSearchPost400ResponseValidationErrorsInner from './com.lodgea.model/LocationSearchPost400ResponseValidationErrorsInner';
import LocationSearchPostRequest from './com.lodgea.model/LocationSearchPostRequest';
import PropertiesGet200Response from './com.lodgea.model/PropertiesGet200Response';
import PropertiesGet200ResponseListInner from './com.lodgea.model/PropertiesGet200ResponseListInner';
import PropertiesPropertyIdAvailabilityGet200Response from './com.lodgea.model/PropertiesPropertyIdAvailabilityGet200Response';
import PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner from './com.lodgea.model/PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner';
import PropertiesPropertyIdGet200Response from './com.lodgea.model/PropertiesPropertyIdGet200Response';
import PropertiesPropertyIdGet200ResponseProductListInner from './com.lodgea.model/PropertiesPropertyIdGet200ResponseProductListInner';
import PropertiesPropertyIdGet200ResponseProductListInnerPolicyInfo from './com.lodgea.model/PropertiesPropertyIdGet200ResponseProductListInnerPolicyInfo';
import PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInner from './com.lodgea.model/PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInner';
import PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner from './com.lodgea.model/PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner';
import PropertiesPropertyIdGet200ResponseProperty from './com.lodgea.model/PropertiesPropertyIdGet200ResponseProperty';
import PropertiesPropertyIdGet200ResponsePropertyAwardListInner from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyAwardListInner';
import PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod';
import PropertiesPropertyIdGet200ResponsePropertyContactListInner from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyContactListInner';
import PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner';
import PropertiesPropertyIdGet200ResponsePropertyFacilityInfo from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyFacilityInfo';
import PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner';
import PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerAmenityListInner from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerAmenityListInner';
import PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner';
import PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMessageListInner from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMessageListInner';
import PropertiesPropertyIdGet200ResponsePropertyGuestInfo from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyGuestInfo';
import PropertiesPropertyIdGet200ResponsePropertyPolicyListInner from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyPolicyListInner';
import PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner';
import PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerFeePolicyListInner from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerFeePolicyListInner';
import PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerGuaranteePolicy from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerGuaranteePolicy';
import PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerPetsPolicy from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerPetsPolicy';
import PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerTaxPolicyListInner from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerTaxPolicyListInner';
import PropertiesPropertyIdGet200ResponsePropertyPropertyInfo from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyPropertyInfo';
import PropertiesPropertyIdGet200ResponsePropertyPropertyInfoAcceptedPaymentListInner from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyPropertyInfoAcceptedPaymentListInner';
import PropertiesPropertyIdGet200ResponsePropertyPropertyInfoMessageListInner from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyPropertyInfoMessageListInner';
import PropertiesPropertyIdGet200ResponsePropertyRecordCreated from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyRecordCreated';
import PropertiesPropertyIdGet200ResponsePropertyRecordModified from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyRecordModified';
import PropertiesPropertyIdGet200ResponsePropertyServiceListInner from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyServiceListInner';
import PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner from './com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner';
import DefaultApi from './com.lodgea.controllers/DefaultApi';


/**
* LODGEA SDK for javascript. Check out https://docs.lodgea.io for more information..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var LodgeaJs = require('com.lodgea/index'); // See note below*.
* var xxxSvc = new LodgeaJs.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new LodgeaJs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['com.lodgea/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new LodgeaJs.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new LodgeaJs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module com.lodgea/index
* @version 1.1.5
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:com.lodgea/ApiClient}
     */
    ApiClient,

    /**
     * The AvailabilitySearchPost200Response model constructor.
     * @property {module:com.lodgea/com.lodgea.model/AvailabilitySearchPost200Response}
     */
    AvailabilitySearchPost200Response,

    /**
     * The AvailabilitySearchPostRequest model constructor.
     * @property {module:com.lodgea/com.lodgea.model/AvailabilitySearchPostRequest}
     */
    AvailabilitySearchPostRequest,

    /**
     * The AvailablePropertiesInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/AvailablePropertiesInner}
     */
    AvailablePropertiesInner,

    /**
     * The AvailablePropertiesInner1 model constructor.
     * @property {module:com.lodgea/com.lodgea.model/AvailablePropertiesInner1}
     */
    AvailablePropertiesInner1,

    /**
     * The AvailablePropertiesInner1AttractionListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/AvailablePropertiesInner1AttractionListInner}
     */
    AvailablePropertiesInner1AttractionListInner,

    /**
     * The AvailablePropertiesInner1AttractionListInnerDistance model constructor.
     * @property {module:com.lodgea/com.lodgea.model/AvailablePropertiesInner1AttractionListInnerDistance}
     */
    AvailablePropertiesInner1AttractionListInnerDistance,

    /**
     * The AvailablePropertiesInner1Geo model constructor.
     * @property {module:com.lodgea/com.lodgea.model/AvailablePropertiesInner1Geo}
     */
    AvailablePropertiesInner1Geo,

    /**
     * The AvailablePropertiesInner1GeoLocation model constructor.
     * @property {module:com.lodgea/com.lodgea.model/AvailablePropertiesInner1GeoLocation}
     */
    AvailablePropertiesInner1GeoLocation,

    /**
     * The AvailablePropertiesInner1LowestPrice model constructor.
     * @property {module:com.lodgea/com.lodgea.model/AvailablePropertiesInner1LowestPrice}
     */
    AvailablePropertiesInner1LowestPrice,

    /**
     * The AvailablePropertiesInner1MediaListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/AvailablePropertiesInner1MediaListInner}
     */
    AvailablePropertiesInner1MediaListInner,

    /**
     * The LocationSearchPost200Response model constructor.
     * @property {module:com.lodgea/com.lodgea.model/LocationSearchPost200Response}
     */
    LocationSearchPost200Response,

    /**
     * The LocationSearchPost400Response model constructor.
     * @property {module:com.lodgea/com.lodgea.model/LocationSearchPost400Response}
     */
    LocationSearchPost400Response,

    /**
     * The LocationSearchPost400ResponseValidationErrorsInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/LocationSearchPost400ResponseValidationErrorsInner}
     */
    LocationSearchPost400ResponseValidationErrorsInner,

    /**
     * The LocationSearchPostRequest model constructor.
     * @property {module:com.lodgea/com.lodgea.model/LocationSearchPostRequest}
     */
    LocationSearchPostRequest,

    /**
     * The PropertiesGet200Response model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesGet200Response}
     */
    PropertiesGet200Response,

    /**
     * The PropertiesGet200ResponseListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesGet200ResponseListInner}
     */
    PropertiesGet200ResponseListInner,

    /**
     * The PropertiesPropertyIdAvailabilityGet200Response model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdAvailabilityGet200Response}
     */
    PropertiesPropertyIdAvailabilityGet200Response,

    /**
     * The PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner}
     */
    PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner,

    /**
     * The PropertiesPropertyIdGet200Response model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200Response}
     */
    PropertiesPropertyIdGet200Response,

    /**
     * The PropertiesPropertyIdGet200ResponseProductListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponseProductListInner}
     */
    PropertiesPropertyIdGet200ResponseProductListInner,

    /**
     * The PropertiesPropertyIdGet200ResponseProductListInnerPolicyInfo model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponseProductListInnerPolicyInfo}
     */
    PropertiesPropertyIdGet200ResponseProductListInnerPolicyInfo,

    /**
     * The PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInner}
     */
    PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInner,

    /**
     * The PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner}
     */
    PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner,

    /**
     * The PropertiesPropertyIdGet200ResponseProperty model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponseProperty}
     */
    PropertiesPropertyIdGet200ResponseProperty,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyAwardListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyAwardListInner}
     */
    PropertiesPropertyIdGet200ResponsePropertyAwardListInner,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod}
     */
    PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyContactListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyContactListInner}
     */
    PropertiesPropertyIdGet200ResponsePropertyContactListInner,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner}
     */
    PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyFacilityInfo model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyFacilityInfo}
     */
    PropertiesPropertyIdGet200ResponsePropertyFacilityInfo,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner}
     */
    PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerAmenityListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerAmenityListInner}
     */
    PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerAmenityListInner,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner}
     */
    PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMessageListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMessageListInner}
     */
    PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMessageListInner,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyGuestInfo model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyGuestInfo}
     */
    PropertiesPropertyIdGet200ResponsePropertyGuestInfo,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyPolicyListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyPolicyListInner}
     */
    PropertiesPropertyIdGet200ResponsePropertyPolicyListInner,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner}
     */
    PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerFeePolicyListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerFeePolicyListInner}
     */
    PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerFeePolicyListInner,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerGuaranteePolicy model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerGuaranteePolicy}
     */
    PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerGuaranteePolicy,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerPetsPolicy model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerPetsPolicy}
     */
    PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerPetsPolicy,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerTaxPolicyListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerTaxPolicyListInner}
     */
    PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerTaxPolicyListInner,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyPropertyInfo model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyPropertyInfo}
     */
    PropertiesPropertyIdGet200ResponsePropertyPropertyInfo,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyPropertyInfoAcceptedPaymentListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyPropertyInfoAcceptedPaymentListInner}
     */
    PropertiesPropertyIdGet200ResponsePropertyPropertyInfoAcceptedPaymentListInner,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyPropertyInfoMessageListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyPropertyInfoMessageListInner}
     */
    PropertiesPropertyIdGet200ResponsePropertyPropertyInfoMessageListInner,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyRecordCreated model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyRecordCreated}
     */
    PropertiesPropertyIdGet200ResponsePropertyRecordCreated,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyRecordModified model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyRecordModified}
     */
    PropertiesPropertyIdGet200ResponsePropertyRecordModified,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyServiceListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyServiceListInner}
     */
    PropertiesPropertyIdGet200ResponsePropertyServiceListInner,

    /**
     * The PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner model constructor.
     * @property {module:com.lodgea/com.lodgea.model/PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner}
     */
    PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner,

    /**
    * The DefaultApi service constructor.
    * @property {module:com.lodgea/com.lodgea.controllers/DefaultApi}
    */
    DefaultApi
};
