/**
 * lodgea-js
 * LODGEA SDK for javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import InlineObject from './com.lodgea.model/InlineObject';
import InlineObject1 from './com.lodgea.model/InlineObject1';
import InlineResponse200 from './com.lodgea.model/InlineResponse200';
import InlineResponse2001 from './com.lodgea.model/InlineResponse2001';
import InlineResponse2001AttractionList from './com.lodgea.model/InlineResponse2001AttractionList';
import InlineResponse2001Distance from './com.lodgea.model/InlineResponse2001Distance';
import InlineResponse2001Geo from './com.lodgea.model/InlineResponse2001Geo';
import InlineResponse2001GeoLocation from './com.lodgea.model/InlineResponse2001GeoLocation';
import InlineResponse2001List from './com.lodgea.model/InlineResponse2001List';
import InlineResponse2001LowestPrice from './com.lodgea.model/InlineResponse2001LowestPrice';
import InlineResponse2001MediaList from './com.lodgea.model/InlineResponse2001MediaList';
import InlineResponse2002 from './com.lodgea.model/InlineResponse2002';
import InlineResponse2002List from './com.lodgea.model/InlineResponse2002List';
import InlineResponse2003 from './com.lodgea.model/InlineResponse2003';
import InlineResponse2003PolicyInfo from './com.lodgea.model/InlineResponse2003PolicyInfo';
import InlineResponse2003PolicyInfoFeePolicyList from './com.lodgea.model/InlineResponse2003PolicyInfoFeePolicyList';
import InlineResponse2003PolicyInfoTaxPolicyList from './com.lodgea.model/InlineResponse2003PolicyInfoTaxPolicyList';
import InlineResponse2003PricingList from './com.lodgea.model/InlineResponse2003PricingList';
import InlineResponse2003ProductList from './com.lodgea.model/InlineResponse2003ProductList';
import InlineResponse2003Property from './com.lodgea.model/InlineResponse2003Property';
import InlineResponse2003PropertyAddressList from './com.lodgea.model/InlineResponse2003PropertyAddressList';
import InlineResponse2003PropertyAwardList from './com.lodgea.model/InlineResponse2003PropertyAwardList';
import InlineResponse2003PropertyCancellationGracePeriod from './com.lodgea.model/InlineResponse2003PropertyCancellationGracePeriod';
import InlineResponse2003PropertyCancellationPolicyList from './com.lodgea.model/InlineResponse2003PropertyCancellationPolicyList';
import InlineResponse2003PropertyContactList from './com.lodgea.model/InlineResponse2003PropertyContactList';
import InlineResponse2003PropertyFacilityInfo from './com.lodgea.model/InlineResponse2003PropertyFacilityInfo';
import InlineResponse2003PropertyFacilityInfoAmenityList from './com.lodgea.model/InlineResponse2003PropertyFacilityInfoAmenityList';
import InlineResponse2003PropertyFacilityInfoGuestRoomList from './com.lodgea.model/InlineResponse2003PropertyFacilityInfoGuestRoomList';
import InlineResponse2003PropertyFacilityInfoMediaList from './com.lodgea.model/InlineResponse2003PropertyFacilityInfoMediaList';
import InlineResponse2003PropertyFacilityInfoMessageList from './com.lodgea.model/InlineResponse2003PropertyFacilityInfoMessageList';
import InlineResponse2003PropertyFeePolicyList from './com.lodgea.model/InlineResponse2003PropertyFeePolicyList';
import InlineResponse2003PropertyGuaranteePolicy from './com.lodgea.model/InlineResponse2003PropertyGuaranteePolicy';
import InlineResponse2003PropertyGuestInfo from './com.lodgea.model/InlineResponse2003PropertyGuestInfo';
import InlineResponse2003PropertyMediaList from './com.lodgea.model/InlineResponse2003PropertyMediaList';
import InlineResponse2003PropertyOperationTimeList from './com.lodgea.model/InlineResponse2003PropertyOperationTimeList';
import InlineResponse2003PropertyPetsPolicy from './com.lodgea.model/InlineResponse2003PropertyPetsPolicy';
import InlineResponse2003PropertyPolicyList from './com.lodgea.model/InlineResponse2003PropertyPolicyList';
import InlineResponse2003PropertyPropertyInfo from './com.lodgea.model/InlineResponse2003PropertyPropertyInfo';
import InlineResponse2003PropertyPropertyInfoAcceptedPaymentList from './com.lodgea.model/InlineResponse2003PropertyPropertyInfoAcceptedPaymentList';
import InlineResponse2003PropertyPropertyInfoMessageList from './com.lodgea.model/InlineResponse2003PropertyPropertyInfoMessageList';
import InlineResponse2003PropertyRecordCreated from './com.lodgea.model/InlineResponse2003PropertyRecordCreated';
import InlineResponse2003PropertyRecordModified from './com.lodgea.model/InlineResponse2003PropertyRecordModified';
import InlineResponse2003PropertyServiceList from './com.lodgea.model/InlineResponse2003PropertyServiceList';
import InlineResponse2003PropertyTaxPolicyList from './com.lodgea.model/InlineResponse2003PropertyTaxPolicyList';
import InlineResponse2003RatePlanList from './com.lodgea.model/InlineResponse2003RatePlanList';
import InlineResponse2004 from './com.lodgea.model/InlineResponse2004';
import InlineResponse2004AvailabilityList from './com.lodgea.model/InlineResponse2004AvailabilityList';
import InlineResponse2004PricingList from './com.lodgea.model/InlineResponse2004PricingList';
import InlineResponse2004RatePlanList from './com.lodgea.model/InlineResponse2004RatePlanList';
import InlineResponse200List from './com.lodgea.model/InlineResponse200List';
import InlineResponse400 from './com.lodgea.model/InlineResponse400';
import InlineResponse4001 from './com.lodgea.model/InlineResponse4001';
import InlineResponse4001ValidationErrors from './com.lodgea.model/InlineResponse4001ValidationErrors';
import InlineResponse400ValidationErrors from './com.lodgea.model/InlineResponse400ValidationErrors';
import DefaultApi from './com.lodgea.controllers/DefaultApi';


/**
* LODGEA_SDK_for_javascript__Check_out_https__docs_lodgea_io_for_more_information_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var LodgeaJs = require('com.lodgea/index'); // See note below*.
* var xxxSvc = new LodgeaJs.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new LodgeaJs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['com.lodgea/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new LodgeaJs.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new LodgeaJs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module com.lodgea/index
* @version 1.2.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:com.lodgea/ApiClient}
     */
    ApiClient,

    /**
     * The InlineObject model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineObject}
     */
    InlineObject,

    /**
     * The InlineObject1 model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineObject1}
     */
    InlineObject1,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse2001AttractionList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2001AttractionList}
     */
    InlineResponse2001AttractionList,

    /**
     * The InlineResponse2001Distance model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2001Distance}
     */
    InlineResponse2001Distance,

    /**
     * The InlineResponse2001Geo model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2001Geo}
     */
    InlineResponse2001Geo,

    /**
     * The InlineResponse2001GeoLocation model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2001GeoLocation}
     */
    InlineResponse2001GeoLocation,

    /**
     * The InlineResponse2001List model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2001List}
     */
    InlineResponse2001List,

    /**
     * The InlineResponse2001LowestPrice model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2001LowestPrice}
     */
    InlineResponse2001LowestPrice,

    /**
     * The InlineResponse2001MediaList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2001MediaList}
     */
    InlineResponse2001MediaList,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2002List model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2002List}
     */
    InlineResponse2002List,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse2003PolicyInfo model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PolicyInfo}
     */
    InlineResponse2003PolicyInfo,

    /**
     * The InlineResponse2003PolicyInfoFeePolicyList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PolicyInfoFeePolicyList}
     */
    InlineResponse2003PolicyInfoFeePolicyList,

    /**
     * The InlineResponse2003PolicyInfoTaxPolicyList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PolicyInfoTaxPolicyList}
     */
    InlineResponse2003PolicyInfoTaxPolicyList,

    /**
     * The InlineResponse2003PricingList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PricingList}
     */
    InlineResponse2003PricingList,

    /**
     * The InlineResponse2003ProductList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003ProductList}
     */
    InlineResponse2003ProductList,

    /**
     * The InlineResponse2003Property model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003Property}
     */
    InlineResponse2003Property,

    /**
     * The InlineResponse2003PropertyAddressList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyAddressList}
     */
    InlineResponse2003PropertyAddressList,

    /**
     * The InlineResponse2003PropertyAwardList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyAwardList}
     */
    InlineResponse2003PropertyAwardList,

    /**
     * The InlineResponse2003PropertyCancellationGracePeriod model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyCancellationGracePeriod}
     */
    InlineResponse2003PropertyCancellationGracePeriod,

    /**
     * The InlineResponse2003PropertyCancellationPolicyList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyCancellationPolicyList}
     */
    InlineResponse2003PropertyCancellationPolicyList,

    /**
     * The InlineResponse2003PropertyContactList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyContactList}
     */
    InlineResponse2003PropertyContactList,

    /**
     * The InlineResponse2003PropertyFacilityInfo model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyFacilityInfo}
     */
    InlineResponse2003PropertyFacilityInfo,

    /**
     * The InlineResponse2003PropertyFacilityInfoAmenityList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyFacilityInfoAmenityList}
     */
    InlineResponse2003PropertyFacilityInfoAmenityList,

    /**
     * The InlineResponse2003PropertyFacilityInfoGuestRoomList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyFacilityInfoGuestRoomList}
     */
    InlineResponse2003PropertyFacilityInfoGuestRoomList,

    /**
     * The InlineResponse2003PropertyFacilityInfoMediaList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyFacilityInfoMediaList}
     */
    InlineResponse2003PropertyFacilityInfoMediaList,

    /**
     * The InlineResponse2003PropertyFacilityInfoMessageList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyFacilityInfoMessageList}
     */
    InlineResponse2003PropertyFacilityInfoMessageList,

    /**
     * The InlineResponse2003PropertyFeePolicyList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyFeePolicyList}
     */
    InlineResponse2003PropertyFeePolicyList,

    /**
     * The InlineResponse2003PropertyGuaranteePolicy model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyGuaranteePolicy}
     */
    InlineResponse2003PropertyGuaranteePolicy,

    /**
     * The InlineResponse2003PropertyGuestInfo model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyGuestInfo}
     */
    InlineResponse2003PropertyGuestInfo,

    /**
     * The InlineResponse2003PropertyMediaList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyMediaList}
     */
    InlineResponse2003PropertyMediaList,

    /**
     * The InlineResponse2003PropertyOperationTimeList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyOperationTimeList}
     */
    InlineResponse2003PropertyOperationTimeList,

    /**
     * The InlineResponse2003PropertyPetsPolicy model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyPetsPolicy}
     */
    InlineResponse2003PropertyPetsPolicy,

    /**
     * The InlineResponse2003PropertyPolicyList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyPolicyList}
     */
    InlineResponse2003PropertyPolicyList,

    /**
     * The InlineResponse2003PropertyPropertyInfo model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyPropertyInfo}
     */
    InlineResponse2003PropertyPropertyInfo,

    /**
     * The InlineResponse2003PropertyPropertyInfoAcceptedPaymentList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyPropertyInfoAcceptedPaymentList}
     */
    InlineResponse2003PropertyPropertyInfoAcceptedPaymentList,

    /**
     * The InlineResponse2003PropertyPropertyInfoMessageList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyPropertyInfoMessageList}
     */
    InlineResponse2003PropertyPropertyInfoMessageList,

    /**
     * The InlineResponse2003PropertyRecordCreated model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyRecordCreated}
     */
    InlineResponse2003PropertyRecordCreated,

    /**
     * The InlineResponse2003PropertyRecordModified model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyRecordModified}
     */
    InlineResponse2003PropertyRecordModified,

    /**
     * The InlineResponse2003PropertyServiceList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyServiceList}
     */
    InlineResponse2003PropertyServiceList,

    /**
     * The InlineResponse2003PropertyTaxPolicyList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003PropertyTaxPolicyList}
     */
    InlineResponse2003PropertyTaxPolicyList,

    /**
     * The InlineResponse2003RatePlanList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2003RatePlanList}
     */
    InlineResponse2003RatePlanList,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse2004AvailabilityList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2004AvailabilityList}
     */
    InlineResponse2004AvailabilityList,

    /**
     * The InlineResponse2004PricingList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2004PricingList}
     */
    InlineResponse2004PricingList,

    /**
     * The InlineResponse2004RatePlanList model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse2004RatePlanList}
     */
    InlineResponse2004RatePlanList,

    /**
     * The InlineResponse200List model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse200List}
     */
    InlineResponse200List,

    /**
     * The InlineResponse400 model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse400}
     */
    InlineResponse400,

    /**
     * The InlineResponse4001 model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse4001}
     */
    InlineResponse4001,

    /**
     * The InlineResponse4001ValidationErrors model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse4001ValidationErrors}
     */
    InlineResponse4001ValidationErrors,

    /**
     * The InlineResponse400ValidationErrors model constructor.
     * @property {module:com.lodgea/com.lodgea.model/InlineResponse400ValidationErrors}
     */
    InlineResponse400ValidationErrors,

    /**
    * The DefaultApi service constructor.
    * @property {module:com.lodgea/com.lodgea.controllers/DefaultApi}
    */
    DefaultApi
};
