/**
 * lodgea-js
 * LODGEA SDK for Javascript. Check out https://lodgea.redoc.ly for more information.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1PropertyGetPost200ResponsePropertyContactListInnerAddressListInner model module.
 * @module model/V1PropertyGetPost200ResponsePropertyContactListInnerAddressListInner
 * @version 1.0.0
 */
class V1PropertyGetPost200ResponsePropertyContactListInnerAddressListInner {
    /**
     * Constructs a new <code>V1PropertyGetPost200ResponsePropertyContactListInnerAddressListInner</code>.
     * @alias module:model/V1PropertyGetPost200ResponsePropertyContactListInnerAddressListInner
     */
    constructor() { 
        
        V1PropertyGetPost200ResponsePropertyContactListInnerAddressListInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1PropertyGetPost200ResponsePropertyContactListInnerAddressListInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1PropertyGetPost200ResponsePropertyContactListInnerAddressListInner} obj Optional instance to populate.
     * @return {module:model/V1PropertyGetPost200ResponsePropertyContactListInnerAddressListInner} The populated <code>V1PropertyGetPost200ResponsePropertyContactListInnerAddressListInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1PropertyGetPost200ResponsePropertyContactListInnerAddressListInner();

            if (data.hasOwnProperty('addressLine')) {
                obj['addressLine'] = ApiClient.convertToType(data['addressLine'], 'String');
            }
            if (data.hasOwnProperty('propertyName')) {
                obj['propertyName'] = ApiClient.convertToType(data['propertyName'], 'String');
            }
            if (data.hasOwnProperty('cityName')) {
                obj['cityName'] = ApiClient.convertToType(data['cityName'], 'String');
            }
            if (data.hasOwnProperty('postalCode')) {
                obj['postalCode'] = ApiClient.convertToType(data['postalCode'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('countryCode')) {
                obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} addressLine
 */
V1PropertyGetPost200ResponsePropertyContactListInnerAddressListInner.prototype['addressLine'] = undefined;

/**
 * @member {String} propertyName
 */
V1PropertyGetPost200ResponsePropertyContactListInnerAddressListInner.prototype['propertyName'] = undefined;

/**
 * @member {String} cityName
 */
V1PropertyGetPost200ResponsePropertyContactListInnerAddressListInner.prototype['cityName'] = undefined;

/**
 * @member {String} postalCode
 */
V1PropertyGetPost200ResponsePropertyContactListInnerAddressListInner.prototype['postalCode'] = undefined;

/**
 * @member {String} state
 */
V1PropertyGetPost200ResponsePropertyContactListInnerAddressListInner.prototype['state'] = undefined;

/**
 * @member {String} countryCode
 */
V1PropertyGetPost200ResponsePropertyContactListInnerAddressListInner.prototype['countryCode'] = undefined;






export default V1PropertyGetPost200ResponsePropertyContactListInnerAddressListInner;

