/**
 * lodgea-js
 * LODGEA SDK for Javascript. Check out https://lodgea.redoc.ly for more information.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1PropertyGetPost200ResponsePropertyMediaListInnerTagListInner from './V1PropertyGetPost200ResponsePropertyMediaListInnerTagListInner';

/**
 * The V1PropertyGetPost200ResponsePropertyMediaListInner model module.
 * @module model/V1PropertyGetPost200ResponsePropertyMediaListInner
 * @version 1.0.0
 */
class V1PropertyGetPost200ResponsePropertyMediaListInner {
    /**
     * Constructs a new <code>V1PropertyGetPost200ResponsePropertyMediaListInner</code>.
     * @alias module:model/V1PropertyGetPost200ResponsePropertyMediaListInner
     */
    constructor() { 
        
        V1PropertyGetPost200ResponsePropertyMediaListInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1PropertyGetPost200ResponsePropertyMediaListInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1PropertyGetPost200ResponsePropertyMediaListInner} obj Optional instance to populate.
     * @return {module:model/V1PropertyGetPost200ResponsePropertyMediaListInner} The populated <code>V1PropertyGetPost200ResponsePropertyMediaListInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1PropertyGetPost200ResponsePropertyMediaListInner();

            if (data.hasOwnProperty('isMainImage')) {
                obj['isMainImage'] = ApiClient.convertToType(data['isMainImage'], 'Boolean');
            }
            if (data.hasOwnProperty('sortOrder')) {
                obj['sortOrder'] = ApiClient.convertToType(data['sortOrder'], 'Number');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('tagList')) {
                obj['tagList'] = ApiClient.convertToType(data['tagList'], [V1PropertyGetPost200ResponsePropertyMediaListInnerTagListInner]);
            }
            if (data.hasOwnProperty('moderationLabelList')) {
                obj['moderationLabelList'] = ApiClient.convertToType(data['moderationLabelList'], ['String']);
            }
            if (data.hasOwnProperty('detectionLabelList')) {
                obj['detectionLabelList'] = ApiClient.convertToType(data['detectionLabelList'], ['String']);
            }
            if (data.hasOwnProperty('propertyAmenityList')) {
                obj['propertyAmenityList'] = ApiClient.convertToType(data['propertyAmenityList'], ['String']);
            }
            if (data.hasOwnProperty('roomAmenityList')) {
                obj['roomAmenityList'] = ApiClient.convertToType(data['roomAmenityList'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} isMainImage
 */
V1PropertyGetPost200ResponsePropertyMediaListInner.prototype['isMainImage'] = undefined;

/**
 * @member {Number} sortOrder
 */
V1PropertyGetPost200ResponsePropertyMediaListInner.prototype['sortOrder'] = undefined;

/**
 * @member {String} url
 */
V1PropertyGetPost200ResponsePropertyMediaListInner.prototype['url'] = undefined;

/**
 * @member {Array.<module:model/V1PropertyGetPost200ResponsePropertyMediaListInnerTagListInner>} tagList
 */
V1PropertyGetPost200ResponsePropertyMediaListInner.prototype['tagList'] = undefined;

/**
 * @member {Array.<String>} moderationLabelList
 */
V1PropertyGetPost200ResponsePropertyMediaListInner.prototype['moderationLabelList'] = undefined;

/**
 * @member {Array.<String>} detectionLabelList
 */
V1PropertyGetPost200ResponsePropertyMediaListInner.prototype['detectionLabelList'] = undefined;

/**
 * @member {Array.<String>} propertyAmenityList
 */
V1PropertyGetPost200ResponsePropertyMediaListInner.prototype['propertyAmenityList'] = undefined;

/**
 * @member {Array.<String>} roomAmenityList
 */
V1PropertyGetPost200ResponsePropertyMediaListInner.prototype['roomAmenityList'] = undefined;






export default V1PropertyGetPost200ResponsePropertyMediaListInner;

