/**
 * lodgea-js
 * LODGEA SDK for Javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/com.lodgea/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/com.lodgea/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LodgeaJs);
  }
}(this, function(expect, LodgeaJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LodgeaJs.AvailabilitySearchPostRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AvailabilitySearchPostRequest', function() {
    it('should create an instance of AvailabilitySearchPostRequest', function() {
      // uncomment below and update the code to test AvailabilitySearchPostRequest
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be.a(LodgeaJs.AvailabilitySearchPostRequest);
    });

    it('should have the property adultCount (base name: "adultCount")', function() {
      // uncomment below and update the code to test the property adultCount
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property childCount (base name: "childCount")', function() {
      // uncomment below and update the code to test the property childCount
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property childAgeList (base name: "childAgeList")', function() {
      // uncomment below and update the code to test the property childAgeList
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property currencyCode (base name: "currencyCode")', function() {
      // uncomment below and update the code to test the property currencyCode
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property languageCode (base name: "languageCode")', function() {
      // uncomment below and update the code to test the property languageCode
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property unitSystem (base name: "unitSystem")', function() {
      // uncomment below and update the code to test the property unitSystem
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property minLengthOfStay (base name: "minLengthOfStay")', function() {
      // uncomment below and update the code to test the property minLengthOfStay
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property maxLengthOfStay (base name: "maxLengthOfStay")', function() {
      // uncomment below and update the code to test the property maxLengthOfStay
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property locationName (base name: "locationName")', function() {
      // uncomment below and update the code to test the property locationName
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property locationType (base name: "locationType")', function() {
      // uncomment below and update the code to test the property locationType
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property earliestArrival (base name: "earliestArrival")', function() {
      // uncomment below and update the code to test the property earliestArrival
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property latestReturn (base name: "latestReturn")', function() {
      // uncomment below and update the code to test the property latestReturn
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property sort (base name: "sort")', function() {
      // uncomment below and update the code to test the property sort
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property serviceList (base name: "serviceList")', function() {
      // uncomment below and update the code to test the property serviceList
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property typeList (base name: "typeList")', function() {
      // uncomment below and update the code to test the property typeList
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property unitTypeList (base name: "unitTypeList")', function() {
      // uncomment below and update the code to test the property unitTypeList
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property unitAmenityList (base name: "unitAmenityList")', function() {
      // uncomment below and update the code to test the property unitAmenityList
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property mealPlanList (base name: "mealPlanList")', function() {
      // uncomment below and update the code to test the property mealPlanList
      //var instance = new LodgeaJs.AvailabilitySearchPostRequest();
      //expect(instance).to.be();
    });

  });

}));
