/**
 * lodgea-js
 * LODGEA SDK for javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/com.lodgea/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/com.lodgea/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LodgeaJs);
  }
}(this, function(expect, LodgeaJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LodgeaJs.InlineResponse2003PropertyFacilityInfoMediaList();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2003PropertyFacilityInfoMediaList', function() {
    it('should create an instance of InlineResponse2003PropertyFacilityInfoMediaList', function() {
      // uncomment below and update the code to test InlineResponse2003PropertyFacilityInfoMediaList
      //var instance = new LodgeaJs.InlineResponse2003PropertyFacilityInfoMediaList();
      //expect(instance).to.be.a(LodgeaJs.InlineResponse2003PropertyFacilityInfoMediaList);
    });

    it('should have the property isMainImage (base name: "isMainImage")', function() {
      // uncomment below and update the code to test the property isMainImage
      //var instance = new LodgeaJs.InlineResponse2003PropertyFacilityInfoMediaList();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new LodgeaJs.InlineResponse2003PropertyFacilityInfoMediaList();
      //expect(instance).to.be();
    });

    it('should have the property sortOrder (base name: "sortOrder")', function() {
      // uncomment below and update the code to test the property sortOrder
      //var instance = new LodgeaJs.InlineResponse2003PropertyFacilityInfoMediaList();
      //expect(instance).to.be();
    });

    it('should have the property tagList (base name: "tagList")', function() {
      // uncomment below and update the code to test the property tagList
      //var instance = new LodgeaJs.InlineResponse2003PropertyFacilityInfoMediaList();
      //expect(instance).to.be();
    });

    it('should have the property moderationLabelList (base name: "moderationLabelList")', function() {
      // uncomment below and update the code to test the property moderationLabelList
      //var instance = new LodgeaJs.InlineResponse2003PropertyFacilityInfoMediaList();
      //expect(instance).to.be();
    });

    it('should have the property detectionLabelList (base name: "detectionLabelList")', function() {
      // uncomment below and update the code to test the property detectionLabelList
      //var instance = new LodgeaJs.InlineResponse2003PropertyFacilityInfoMediaList();
      //expect(instance).to.be();
    });

    it('should have the property propertyAmenityList (base name: "propertyAmenityList")', function() {
      // uncomment below and update the code to test the property propertyAmenityList
      //var instance = new LodgeaJs.InlineResponse2003PropertyFacilityInfoMediaList();
      //expect(instance).to.be();
    });

    it('should have the property roomAmenityList (base name: "roomAmenityList")', function() {
      // uncomment below and update the code to test the property roomAmenityList
      //var instance = new LodgeaJs.InlineResponse2003PropertyFacilityInfoMediaList();
      //expect(instance).to.be();
    });

  });

}));
