/**
 * lodgea-js
 * LODGEA SDK for Javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/com.lodgea/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/com.lodgea/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LodgeaJs);
  }
}(this, function(expect, LodgeaJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LodgeaJs.PropertiesPropertyIdGet200ResponsePropertyPolicyListInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PropertiesPropertyIdGet200ResponsePropertyPolicyListInner', function() {
    it('should create an instance of PropertiesPropertyIdGet200ResponsePropertyPolicyListInner', function() {
      // uncomment below and update the code to test PropertiesPropertyIdGet200ResponsePropertyPolicyListInner
      //var instance = new LodgeaJs.PropertiesPropertyIdGet200ResponsePropertyPolicyListInner();
      //expect(instance).to.be.a(LodgeaJs.PropertiesPropertyIdGet200ResponsePropertyPolicyListInner);
    });

    it('should have the property checkInTime (base name: "checkInTime")', function() {
      // uncomment below and update the code to test the property checkInTime
      //var instance = new LodgeaJs.PropertiesPropertyIdGet200ResponsePropertyPolicyListInner();
      //expect(instance).to.be();
    });

    it('should have the property checkOutTime (base name: "checkOutTime")', function() {
      // uncomment below and update the code to test the property checkOutTime
      //var instance = new LodgeaJs.PropertiesPropertyIdGet200ResponsePropertyPolicyListInner();
      //expect(instance).to.be();
    });

    it('should have the property totalGuestCount (base name: "totalGuestCount")', function() {
      // uncomment below and update the code to test the property totalGuestCount
      //var instance = new LodgeaJs.PropertiesPropertyIdGet200ResponsePropertyPolicyListInner();
      //expect(instance).to.be();
    });

    it('should have the property cancellationPolicyList (base name: "cancellationPolicyList")', function() {
      // uncomment below and update the code to test the property cancellationPolicyList
      //var instance = new LodgeaJs.PropertiesPropertyIdGet200ResponsePropertyPolicyListInner();
      //expect(instance).to.be();
    });

    it('should have the property advanceBookingMin (base name: "advanceBookingMin")', function() {
      // uncomment below and update the code to test the property advanceBookingMin
      //var instance = new LodgeaJs.PropertiesPropertyIdGet200ResponsePropertyPolicyListInner();
      //expect(instance).to.be();
    });

    it('should have the property advanceBookingMax (base name: "advanceBookingMax")', function() {
      // uncomment below and update the code to test the property advanceBookingMax
      //var instance = new LodgeaJs.PropertiesPropertyIdGet200ResponsePropertyPolicyListInner();
      //expect(instance).to.be();
    });

    it('should have the property petsPolicy (base name: "petsPolicy")', function() {
      // uncomment below and update the code to test the property petsPolicy
      //var instance = new LodgeaJs.PropertiesPropertyIdGet200ResponsePropertyPolicyListInner();
      //expect(instance).to.be();
    });

    it('should have the property prepaymentPolicy (base name: "prepaymentPolicy")', function() {
      // uncomment below and update the code to test the property prepaymentPolicy
      //var instance = new LodgeaJs.PropertiesPropertyIdGet200ResponsePropertyPolicyListInner();
      //expect(instance).to.be();
    });

    it('should have the property guaranteePolicy (base name: "guaranteePolicy")', function() {
      // uncomment below and update the code to test the property guaranteePolicy
      //var instance = new LodgeaJs.PropertiesPropertyIdGet200ResponsePropertyPolicyListInner();
      //expect(instance).to.be();
    });

    it('should have the property taxPolicyList (base name: "taxPolicyList")', function() {
      // uncomment below and update the code to test the property taxPolicyList
      //var instance = new LodgeaJs.PropertiesPropertyIdGet200ResponsePropertyPolicyListInner();
      //expect(instance).to.be();
    });

    it('should have the property feePolicyList (base name: "feePolicyList")', function() {
      // uncomment below and update the code to test the property feePolicyList
      //var instance = new LodgeaJs.PropertiesPropertyIdGet200ResponsePropertyPolicyListInner();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new LodgeaJs.PropertiesPropertyIdGet200ResponsePropertyPolicyListInner();
      //expect(instance).to.be();
    });

  });

}));
