/**
 * lodgea-js
 * LODGEA SDK for Javascript. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/com.lodgea/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/com.lodgea/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LodgeaJs);
  }
}(this, function(expect, LodgeaJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList', function() {
    it('should create an instance of V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList', function() {
      // uncomment below and update the code to test V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be.a(LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList);
    });

    it('should have the property _3 (base name: "3")', function() {
      // uncomment below and update the code to test the property _3
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be();
    });

    it('should have the property _4 (base name: "4")', function() {
      // uncomment below and update the code to test the property _4
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be();
    });

    it('should have the property _5 (base name: "5")', function() {
      // uncomment below and update the code to test the property _5
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be();
    });

    it('should have the property _6 (base name: "6")', function() {
      // uncomment below and update the code to test the property _6
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be();
    });

    it('should have the property _7 (base name: "7")', function() {
      // uncomment below and update the code to test the property _7
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be();
    });

    it('should have the property _8 (base name: "8")', function() {
      // uncomment below and update the code to test the property _8
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be();
    });

    it('should have the property _9 (base name: "9")', function() {
      // uncomment below and update the code to test the property _9
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be();
    });

    it('should have the property _10 (base name: "10")', function() {
      // uncomment below and update the code to test the property _10
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be();
    });

    it('should have the property _11 (base name: "11")', function() {
      // uncomment below and update the code to test the property _11
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be();
    });

    it('should have the property _12 (base name: "12")', function() {
      // uncomment below and update the code to test the property _12
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be();
    });

    it('should have the property _13 (base name: "13")', function() {
      // uncomment below and update the code to test the property _13
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be();
    });

    it('should have the property _14 (base name: "14")', function() {
      // uncomment below and update the code to test the property _14
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be();
    });

    it('should have the property _15 (base name: "15")', function() {
      // uncomment below and update the code to test the property _15
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be();
    });

    it('should have the property _16 (base name: "16")', function() {
      // uncomment below and update the code to test the property _16
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be();
    });

    it('should have the property _17 (base name: "17")', function() {
      // uncomment below and update the code to test the property _17
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be();
    });

    it('should have the property _18 (base name: "18")', function() {
      // uncomment below and update the code to test the property _18
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be();
    });

    it('should have the property _19 (base name: "19")', function() {
      // uncomment below and update the code to test the property _19
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be();
    });

    it('should have the property _20 (base name: "20")', function() {
      // uncomment below and update the code to test the property _20
      //var instance = new LodgeaJs.V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList();
      //expect(instance).to.be();
    });

  });

}));
